"""Single source of truth for industry onboarding and public-site presets."""

from __future__ import annotations

from . import palette


# ── Visual style presets ─────────────────────────────────────────────────────
#
# GENERATED by `python3 docs/design/palette_gen.py --emit-presets`. Do not edit
# a hex here; change the theme in `docs/design/palette_gen.py` and re-emit.
# `backend/tests/test_theme_layering.py` fails on any drift.
#
# ONE palette, since 2026-08-06. There were eight, one per industry, and the
# arrangement had a cost nobody had measured: the PAPER carried the industry
# hue, so whichever semantic role shared that hue stopped being visible. Five
# of the seven light themes had one — cedar-grove's success sat 4 degrees off
# its own page, harbour-calm's info 9, vintage-press's warning 3. A green
# theme could not show "saved".
#
# So the paper and the ink are anchored and constant, the four semantics are
# constant, and a studio gets one knob: the accent hue, taken from its own
# logo and re-solved (see `accent_hue_from` — the hue is kept, the lightness
# and saturation are the product's). Twenty-eight of the forty-three tokens
# are no longer variables.
#
# The default accent is a deep bronze analogous to the paper rather than the
# violet that maximises distance from the four status hues. That is a decision
# taken against the arithmetic: warm paper with a warm accent reads as one
# room, and a violet reads as a brand colour on a beige page. It is only safe
# because a semantic role is never a solid fill — see `Design_Constraints.md`
# section 1.1 — and because the accent's own tinted chip is solved deeper than
# any status chip, which the generator asserts.
#
#     python3 docs/design/palette_gen.py            # verify
#     python3 docs/design/palette_gen.py --table    # inspect

VISUAL_STYLE_PRESETS: dict[str, dict] = {
    "studio": {
        "label": "Studio", "label_zh": "工作室",
        "description": "Warm paper, near-black warm ink, and a single accent the studio sets from its own logo.",
        "description_zh": "暖纸、近黑暖墨，和一支由工作室自己从 Logo 定下的强调色。",
        "mood": "calm, considered, content-led",
        "harmony": "warm paper / one accent",
        "modes": ['light', 'dark'],
        "themes": {
            "light": {
                "color_scheme": "light", "background_color": "#F4F1EA", "background_alt_color": "#ECE7DA",
                "panel_color": "#FBF9F5", "surface_hover_color": "#F5F2EE", "text_color": "#221F1A",
                "text_soft_color": "#47423B", "muted_text_color": "#6C665B", "border_color": "#E1DBCE",
                "border_strong_color": "#8C826C", "accent_color": "#704B2E", "accent_text_color": "#FFFFFF",
                "accent_muted_text_color": "#CCC8C4", "accent_hover_color": "#5A3C25", "accent_pressed_color": "#452E1C",
                "accent_soft_color": "#DBC9BB", "accent_on_soft_color": "#704B2E", "accent_border_color": "#BDA593",
                "secondary_accent_color": "#576D49", "secondary_soft_color": "#DAE7D1", "secondary_on_soft_color": "#566B48",
                "secondary_border_color": "#B3C2A8", "success_color": "#307A57", "success_soft_color": "#D2E8DE",
                "success_on_soft_color": "#2D7151", "success_border_color": "#A1C6B5", "warning_color": "#8E6426",
                "warning_soft_color": "#EEE1CE", "warning_on_soft_color": "#855D24", "warning_border_color": "#D0BA9A",
                "danger_color": "#B9473B", "danger_soft_color": "#F2DFDA", "danger_on_soft_color": "#AD4237",
                "danger_border_color": "#E1B3AC", "info_color": "#3E6FA8", "info_soft_color": "#DAE4F0",
                "info_on_soft_color": "#3A679D", "info_border_color": "#AAC0DA", "focus_ring_color": "#AC7346",
                "disabled_surface_color": "#E9E3D3", "disabled_text_color": "#878178", "scrim_color": "rgba(0,0,0,0.5)",
            },
            "dark": {
                "color_scheme": "dark", "background_color": "#14120F", "background_alt_color": "#1E1B16",
                "panel_color": "#2C2921", "surface_hover_color": "#302E26", "text_color": "#E2E0DC",
                "text_soft_color": "#C4C0BA", "muted_text_color": "#979187", "border_color": "#47433B",
                "border_strong_color": "#787366", "accent_color": "#C69E7E", "accent_text_color": "#141210",
                "accent_muted_text_color": "#3E3A36", "accent_hover_color": "#D1B197", "accent_pressed_color": "#DCC3B0",
                "accent_soft_color": "#544234", "accent_on_soft_color": "#CEAC90", "accent_border_color": "#705946",
                "secondary_accent_color": "#90A880", "secondary_soft_color": "#2E3B25", "secondary_on_soft_color": "#90A880",
                "secondary_border_color": "#445439", "success_color": "#378E65", "success_soft_color": "#263C31",
                "success_on_soft_color": "#45B37F", "success_border_color": "#2C5842", "warning_color": "#A5752C",
                "warning_soft_color": "#423622", "warning_on_soft_color": "#CD9642", "warning_border_color": "#644C25",
                "danger_color": "#C85E52", "danger_soft_color": "#48322A", "danger_on_soft_color": "#D88C83",
                "danger_border_color": "#754138", "info_color": "#4C81BD", "info_soft_color": "#2E3844",
                "info_on_soft_color": "#7CA3CF", "info_border_color": "#38516D", "focus_ring_color": "#A06A41",
                "disabled_surface_color": "#27231C", "disabled_text_color": "#716C64", "scrim_color": "rgba(0,0,0,0.66)",
            },
        },
    },
}


# 2026-08-06: the industry no longer chooses a palette, because there is only
# one. What an industry actually differentiates is the vocabulary, the section
# copy, the registration questions and the operational template — which is
# what the marketing page has always claimed ("Templates change the vocabulary
# and the forms, not just the colours") and what the note below this mapping
# used to promise while the code did the opposite.
#
# Colour is now one knob the studio sets from its own logo. A dance studio and
# a maths tutor differ in their words and their photographs; they never
# differed in their hue, and pretending otherwise cost five of the seven
# palettes a visible semantic role — a green theme could not show "saved".
DEFAULT_STYLE_ID = "studio"

# Shape is a presentation choice, not a palette choice, and now that the
# palette no longer varies it is the only preset dimension left in this table.
# The studio can still pick sharp or rounded buttons and a different display
# face without touching a colour.
STYLE_SHAPE = {
    "studio": {"button_style": "soft", "font_mood": "serif"},
}

HARMONY_LABELS: dict[str, dict[str, str]] = {
    "warm paper / one accent": {"zh": "暖纸 · 单一强调色",
                                "en": "Warm paper / one accent"},
}


def harmony_label(harmony: str) -> dict[str, str]:
    """Return the human-readable name of a colour relationship."""

    return dict(HARMONY_LABELS.get(harmony, {"zh": harmony, "en": harmony}))


def style_theme(style_id: str, scheme: str = "light", accent_hue: float | None = None) -> dict:
    """Return one style's flat token map for a given light/dark scheme.

    Falls back to the style's only available mode when the requested one does
    not exist, and to the default style when the id is unknown, so a stale
    tenant setting can never render an empty theme.

    With `accent_hue` the palette is SOLVED rather than read from the generated
    literal above. That is the studio's one colour knob: the hue comes from the
    studio (usually out of its logo), the lightness and saturation stay the
    product's, so a neon logo becomes a deep pine and cannot produce a button
    nobody can read. Without it the literal is used unchanged, which keeps the
    common path free of any solving and keeps the generated file the thing the
    drift tests pin.
    """

    preset = VISUAL_STYLE_PRESETS.get(style_id) or VISUAL_STYLE_PRESETS[DEFAULT_STYLE_ID]
    resolved_id = style_id if style_id in VISUAL_STYLE_PRESETS else DEFAULT_STYLE_ID
    themes = preset["themes"]
    mode = scheme if scheme in themes else preset["modes"][0]
    shape = {
        "style_id": resolved_id,
        "theme_mode": "preset",
        **STYLE_SHAPE.get(resolved_id, STYLE_SHAPE[DEFAULT_STYLE_ID]),
    }
    if accent_hue is None:
        return {**shape, **themes[mode]}
    solved = palette.build(palette.studio_theme(float(accent_hue)), mode == "dark")
    return {**shape, "accent_hue": round(float(accent_hue) % 360, 1), **solved}


def accent_starting_points() -> list[dict]:
    """The swatch shelf the owner picks from before reaching for the picker."""

    return palette.accent_shelf()


def accent_hue_of_colour(value: str) -> float:
    """The hue this product will actually use for a studio-supplied colour."""

    return palette.accent_hue_from(value)


# B1: per-industry section copy. The template shipped one set of headings
# to every tenant, so five live studios all said 「总有一种，适合此刻的你」.
# A parent comparing two of them saw the same sentence twice.
INDUSTRY_SECTION_COPY: dict[str, dict] = {
    "art": {
        "courses_title": {"zh": "总有一种画法，适合此刻的你", "en": "There is a way of making that fits you now"},
        "courses_lead": {"zh": "从第一笔到完整作品，按你的节奏推进。", "en": "From a first mark to a finished piece, at your own pace."},
        "gallery_title": {"zh": "他们画出来的东西", "en": "What our students have made"},
        "gallery_lead": {"zh": "学员在这里完成的作品，经本人同意后展出。", "en": "Made here, shared with each student's consent."},
        "faq_title": {"zh": "动笔之前，先了解这些", "en": "Worth knowing before you start"},
    },
    "music": {
        "courses_title": {"zh": "总有一种节奏，适合此刻的你", "en": "There is a tempo that fits you now"},
        "courses_lead": {"zh": "从识谱到完整曲目，按你的节奏推进。", "en": "From reading notes to a finished piece, at your own pace."},
        "gallery_title": {"zh": "他们弹出来的声音", "en": "What our students have played"},
        "gallery_lead": {"zh": "学员的演奏与曲目记录，经本人同意后展出。", "en": "Recordings and repertoire, shared with each student's consent."},
        "faq_title": {"zh": "坐上琴凳之前，先了解这些", "en": "Worth knowing before the first lesson"},
    },
    "dance": {
        "courses_title": {"zh": "总有一支舞，适合此刻的你", "en": "There is a style that fits you now"},
        "courses_lead": {"zh": "从基本功到成套编排，按你的节奏推进。", "en": "From fundamentals to full choreography, at your own pace."},
        "gallery_title": {"zh": "他们跳出来的样子", "en": "What our dancers have performed"},
        "gallery_lead": {"zh": "课堂与演出的录像，经本人同意后展出。", "en": "Class and stage recordings, shared with each dancer's consent."},
        "faq_title": {"zh": "换上舞鞋之前，先了解这些", "en": "Worth knowing before the first class"},
    },
    "math": {
        "courses_title": {"zh": "总有一条路径，适合此刻的进度", "en": "There is a path that fits where you are now"},
        "courses_lead": {"zh": "先找准知识缺口，再按步骤补齐。", "en": "Find the gaps first, then close them step by step."},
        "gallery_title": {"zh": "他们的进步轨迹", "en": "How our learners have progressed"},
        "gallery_lead": {"zh": "阶段性练习与测评记录，经本人同意后展出。", "en": "Exercises and assessments, shared with each learner's consent."},
        "faq_title": {"zh": "开始补课之前，先了解这些", "en": "Worth knowing before you start"},
    },
    "language": {
        "courses_title": {"zh": "总有一种开口方式，适合此刻的你", "en": "There is a way in that fits you now"},
        "courses_lead": {"zh": "从日常表达到考试准备，按你的节奏推进。", "en": "From everyday conversation to exam prep, at your own pace."},
        "gallery_title": {"zh": "他们说出来的样子", "en": "How our learners are speaking now"},
        "gallery_lead": {"zh": "口语与作业记录，经本人同意后展出。", "en": "Speaking and coursework records, shared with each learner's consent."},
        "faq_title": {"zh": "开口之前，先了解这些", "en": "Worth knowing before you start"},
    },
    "sports": {
        "courses_title": {"zh": "总有一种训练，适合此刻的你", "en": "There is a programme that fits you now"},
        "courses_lead": {"zh": "从体能基础到比赛准备，按你的节奏推进。", "en": "From base fitness to competition, at your own pace."},
        "gallery_title": {"zh": "他们练出来的成绩", "en": "What our athletes have achieved"},
        "gallery_lead": {"zh": "训练与比赛记录，经本人同意后展出。", "en": "Training and competition records, shared with each athlete's consent."},
        "faq_title": {"zh": "开始训练之前，先了解这些", "en": "Worth knowing before your first session"},
    },
    "game": {
        "courses_title": {"zh": "总有一个方向，适合此刻的你", "en": "There is a track that fits you now"},
        "courses_lead": {"zh": "从上手到独立完成作品，按你的节奏推进。", "en": "From first build to shipping your own, at your own pace."},
        "gallery_title": {"zh": "他们做出来的东西", "en": "What our students have built"},
        "gallery_lead": {"zh": "学员完成的项目，经本人同意后展出。", "en": "Projects built here, shared with each student's consent."},
        "faq_title": {"zh": "开始之前，先了解这些", "en": "Worth knowing before you start"},
    },
    "general": {
        "courses_title": {"zh": "总有一种节奏，适合此刻的你", "en": "There is a pace that fits you now"},
        "courses_lead": {"zh": "从零基础到进阶，按你的节奏推进。", "en": "From first steps to advanced, at your own pace."},
        "gallery_title": {"zh": "他们完成的记录", "en": "What our students have made"},
        "gallery_lead": {"zh": "学员在这里完成的记录，经本人同意后展出。", "en": "Made here, shared with each student's consent."},
        "faq_title": {"zh": "开始之前，先了解这些", "en": "Worth knowing before you start"},
    },
}


def _field(
    key: str,
    label_en: str,
    label_zh: str,
    placeholder_en: str,
    placeholder_zh: str,
) -> dict:
    return {
        "key": key,
        "label": label_en,
        "label_en": label_en,
        "label_zh": label_zh,
        "placeholder": placeholder_en,
        "placeholder_en": placeholder_en,
        "placeholder_zh": placeholder_zh,
        "type": "text",
        "required": False,
        "options": [],
    }


INDUSTRY_PRESETS: dict[str, dict] = {
    "art": {
        "label": "Art",
        "label_zh": "艺术",
        "layout": "editorial",
        "slogan": "Create boldly. Grow visibly.", "slogan_zh": "大胆创作，让成长看得见。",
        # `title` is filled in below from the slogan — do not write it here.
        "hero": {
            "subtitle": {"zh": "从兴趣启发到系统表达，记录每一次真实成长。", "en": "From first ideas to confident expression, make every stage of growth visible."},
        },
        "venue_noun": {"zh": "画室", "en": "studio"},
        "work_noun": {"zh": "作品", "en": "work", "en_plural": "works"},
        "registration_title": "Tell us how they like to create",
        "registration_title_zh": "告诉我们学员喜欢怎样创作",
        "copy_pack": {"portal_label": "Art Student Portal", "register_intro": "Three questions about style, experience and goals, then the studio will suggest a class and a time."},
        "register_intro_zh": "三个关于创作形式、经验与目标的问题，之后画室会推荐合适的课程与时间。",
        "theme": {"background_color": "#FFF7F3", "panel_color": "#FFFFFF", "text_color": "#2B2118", "accent_color": "#A23E5C", "secondary_accent_color": "#6B4F3A", "button_style": "soft", "font_mood": "serif"},
        "fields": [
            _field("artStyle", "Preferred style", "喜欢的艺术形式", "Watercolour, sketching, acrylic", "水彩、素描、丙烯等"),
            _field("experience", "Current experience", "目前经验", "Beginner, some experience, portfolio prep", "零基础、有一定经验、作品集准备"),
            _field("goals", "Creative goals", "创作目标", "Relax, build technique, portfolio prep", "培养兴趣、提升技法、准备作品集"),
        ],
    },
    "music": {
        "label": "Music", "label_zh": "音乐", "layout": "performance",
        "slogan": "Find your rhythm. Make every practice count.", "slogan_zh": "找到自己的节奏，让每次练习都算数。",
        "hero": {"subtitle": {"zh": "清晰的目标、适合的节奏与看得见的音乐成长。", "en": "Clear goals, the right pace, and musical progress you can hear."}},
        "venue_noun": {"zh": "琴行", "en": "studio"},
        "work_noun": {"zh": "曲目", "en": "piece", "en_plural": "pieces"},
        "registration_title": "Tell us what they want to play", "registration_title_zh": "告诉我们学员想学什么乐器",
        "copy_pack": {"portal_label": "Music Student Portal", "register_intro": "The instrument, the current level and the goal, then the studio will match a teacher and a lesson time."},
        "register_intro_zh": "乐器、当前水平与音乐目标，之后琴行会匹配合适的老师与上课时间。",
        "theme": {"background_color": "#F7F5FF", "panel_color": "#FFFFFF", "text_color": "#201A35", "accent_color": "#5B3FA8", "secondary_accent_color": "#1F2A44", "button_style": "soft", "font_mood": "classic"},
        "fields": [
            _field("instrument", "Instrument", "乐器或声乐", "Piano, guitar, violin, voice", "钢琴、吉他、小提琴、声乐等"),
            _field("level", "Current level", "当前水平", "Beginner, AMEB Grade 2, self-taught", "零基础、考级程度、自学经验"),
            _field("goals", "Music goals", "音乐目标", "Exam prep, performance, confidence", "考级、演出、兴趣或自信表达"),
        ],
    },
    "math": {
        # `label` is display only — the category key stays "math". Australian
        # spelling, like the rest of the product's copy.
        "label": "Maths", "label_zh": "数学", "layout": "structured",
        "slogan": "Understand the method. Build lasting confidence.", "slogan_zh": "理解方法，建立长久的信心。",
        "hero": {"subtitle": {"zh": "找准知识缺口，用清晰方法建立可持续的学习能力。", "en": "Find the gaps, learn a clear method, and build skills that last."}},
        "venue_noun": {"zh": "教室", "en": "centre"},
        "work_noun": {"zh": "练习", "en": "exercise", "en_plural": "exercises"},
        "registration_title": "Tell us where they are and what is hard", "registration_title_zh": "告诉我们目前的学习阶段与难点",
        "copy_pack": {"portal_label": "Maths Student Portal", "register_intro": "Year level, the topics that are hard, and what you want to reach — the centre replies with a plan."},
        "register_intro_zh": "年级、当前难点与希望达到的目标，教室会给出对应的学习方案。",
        "theme": {"background_color": "#F3F7FF", "panel_color": "#FFFFFF", "text_color": "#172033", "accent_color": "#1D4ED8", "secondary_accent_color": "#0F766E", "button_style": "sharp", "font_mood": "modern"},
        "fields": [
            _field("yearLevel", "Year level", "年级", "Year 5, Year 9, VCE", "五年级、九年级、VCE 等"),
            _field("topics", "Topic focus", "重点内容", "Algebra, fractions, problem solving", "代数、分数、应用题等"),
            _field("goals", "Learning goals", "学习目标", "Catch up, extension, exam confidence", "补基础、拓展、考试信心"),
        ],
    },
    "dance": {
        "label": "Dance", "label_zh": "舞蹈", "layout": "expressive",
        "slogan": "Move with confidence. Grow through practice.", "slogan_zh": "自信地舞动，在训练中成长。",
        "hero": {"subtitle": {"zh": "兼顾技术、体态与舞台表达，让每一步更自信。", "en": "Build technique, presence, and confidence in every movement."}},
        "venue_noun": {"zh": "舞蹈教室", "en": "studio"},
        "work_noun": {"zh": "舞蹈录像", "en": "recording", "en_plural": "recordings"},
        "registration_title": "Tell us about the dancer", "registration_title_zh": "告诉我们舞者的经验与目标",
        "copy_pack": {"portal_label": "Dance Student Portal", "register_intro": "The style, the level and the goal, then the studio will suggest a class and a trial time."},
        "register_intro_zh": "舞种、当前水平与训练目标，之后舞蹈教室会安排合适的班级与试课时间。",
        "theme": {"background_color": "#FFF4F8", "panel_color": "#FFFFFF", "text_color": "#2D1723", "accent_color": "#B4236E", "secondary_accent_color": "#6D315E", "button_style": "rounded", "font_mood": "classic"},
        "fields": [
            _field("danceStyle", "Dance style", "喜欢的舞种", "Ballet, jazz, hip hop, contemporary", "芭蕾、爵士、街舞、现代舞等"),
            _field("level", "Current level", "当前水平", "Beginner, intermediate, exam stream", "零基础、中级、考级方向"),
            _field("goals", "Dance goals", "舞蹈目标", "Fitness, performance, technique", "体能、表演、技术提升"),
        ],
    },
    "language": {
        "label": "Language", "label_zh": "语言", "layout": "friendly",
        "slogan": "Find your voice. Connect with the world.", "slogan_zh": "开口表达，连接更大的世界。",
        "hero": {"subtitle": {"zh": "从真实沟通出发，建立能够长期使用的语言能力。", "en": "Build practical language skills through real communication."}},
        "venue_noun": {"zh": "教室", "en": "centre"},
        "work_noun": {"zh": "练习", "en": "exercise", "en_plural": "exercises"},
        "registration_title": "Tell us which language and what level", "registration_title_zh": "告诉我们学习语言与当前水平",
        "copy_pack": {"portal_label": "Language Student Portal", "register_intro": "Which language, what level, and where you will use it — the centre replies with a class and a time."},
        "register_intro_zh": "目标语言、当前水平与使用场景，教室会推荐合适的课程与上课时间。",
        "theme": {"background_color": "#F2FBFC", "panel_color": "#FFFFFF", "text_color": "#163036", "accent_color": "#0E7490", "secondary_accent_color": "#7C3AED", "button_style": "rounded", "font_mood": "modern"},
        "fields": [
            _field("language", "Language", "目标语言", "English, Mandarin, Japanese, French", "英语、中文、日语、法语等"),
            _field("level", "Current level", "当前水平", "Beginner, conversational, exam prep", "零基础、日常交流、考试准备"),
            _field("goals", "Language goals", "语言目标", "Speaking, school support, travel", "口语、学校辅导、旅行或工作"),
        ],
    },
    "sports": {
        "label": "Sports", "label_zh": "运动", "layout": "energetic",
        "slogan": "Train with purpose. Grow stronger every session.", "slogan_zh": "有目标地训练，一次比一次更强。",
        "hero": {"subtitle": {"zh": "科学训练、清晰反馈与持续进步。", "en": "Purposeful coaching, clear feedback, and steady progress."}},
        "venue_noun": {"zh": "训练中心", "en": "club"},
        "work_noun": {"zh": "训练记录", "en": "session record", "en_plural": "session records"},
        "registration_title": "Tell us the sport and the goal", "registration_title_zh": "告诉我们运动项目与训练目标",
        "copy_pack": {"portal_label": "Sports Student Portal", "register_intro": "The sport, the current level and the goal, then the club will suggest a squad and a session time."},
        "register_intro_zh": "运动项目、当前水平与训练目标，之后训练中心会推荐合适的组别与训练时间。",
        "theme": {"background_color": "#F4FAF5", "panel_color": "#FFFFFF", "text_color": "#17251A", "accent_color": "#166534", "secondary_accent_color": "#B45309", "button_style": "sharp", "font_mood": "modern"},
        "fields": [
            _field("sport", "Sport", "运动项目", "Tennis, swimming, basketball, soccer", "网球、游泳、篮球、足球等"),
            _field("level", "Current level", "当前水平", "Beginner, club, competition", "零基础、俱乐部、比赛级别"),
            _field("goals", "Training goals", "训练目标", "Fitness, technique, competition prep", "体能、技术、比赛准备"),
        ],
    },
    "game": {
        # "Game" dropped the half of the offer the Chinese label keeps: 编程.
        "label": "Games & Coding", "label_zh": "游戏与编程", "layout": "digital",
        "slogan": "Play, think, create, and level up.", "slogan_zh": "在玩中思考、创造与升级。",
        "hero": {"subtitle": {"zh": "把兴趣转化为策略、编程、创造力与团队能力。", "en": "Turn play into strategy, coding, creativity, and teamwork."}},
        "venue_noun": {"zh": "工作室", "en": "studio"},
        "work_noun": {"zh": "项目", "en": "project", "en_plural": "projects"},
        "registration_title": "Tell us what they want to build or play", "registration_title_zh": "告诉我们感兴趣的游戏或编程方向",
        "copy_pack": {"portal_label": "Games & Coding Portal", "register_intro": "What they want to build or play, how much they have done, and what they want to learn — the studio replies with a project and a start date."},
        "register_intro_zh": "想做什么或想玩什么、目前的经验与学习目标，之后工作室会推荐合适的项目与开课时间。",
        "theme": {"background_color": "#F6F4FF", "panel_color": "#FFFFFF", "text_color": "#1F1735", "accent_color": "#5B21B6", "secondary_accent_color": "#0F766E", "button_style": "rounded", "font_mood": "modern"},
        "fields": [
            _field("gameType", "Game or activity", "游戏或活动方向", "Roblox, Minecraft, chess, coding games", "Roblox、Minecraft、国际象棋、编程游戏"),
            _field("level", "Current level", "当前经验", "Beginner, casual, competitive", "零基础、兴趣玩家、竞赛方向"),
            _field("goals", "Learning goals", "学习目标", "Strategy, coding, teamwork, confidence", "策略、编程、团队合作、自信"),
        ],
    },
    "general": {
        "label": "General", "label_zh": "通用", "layout": "neutral",
        "slogan": "A learning path that fits every student.", "slogan_zh": "适合每个学员的成长路径。",
        "hero": {"subtitle": {"zh": "从兴趣和目标出发，在适合的节奏中稳步成长。", "en": "Start with the learner's interests and goals, then grow at the right pace."}},
        "venue_noun": {"zh": "工作室", "en": "studio"},
        "work_noun": {"zh": "作品", "en": "work", "en_plural": "works"},
        "registration_title": "Tell us about the student", "registration_title_zh": "告诉我们学员的兴趣与学习目标",
        "copy_pack": {"portal_label": "Student Portal", "register_intro": "Interests, experience and goals, then the studio will suggest a class and a time."},
        "register_intro_zh": "兴趣方向、当前经验与学习目标，之后工作室会推荐合适的课程与时间。",
        "theme": {"background_color": "#F8FAFC", "panel_color": "#FFFFFF", "text_color": "#1E293B", "accent_color": "#1E40AF", "secondary_accent_color": "#0F766E", "button_style": "soft", "font_mood": "modern"},
        "fields": [
            _field("interests", "Interests", "兴趣方向", "What does the student enjoy?", "学员平时喜欢什么？"),
            _field("experience", "Experience", "当前经验", "Beginner, some experience, advanced", "零基础、有一定经验、进阶"),
            _field("goals", "Goals", "学习目标", "Confidence, skills, exam prep, fun", "自信、技能、考试准备或兴趣"),
        ],
    },
}


def _operational_template(
    courses: list[tuple[str, str]],
    registration_focus: tuple[str, str],
    report_focus: tuple[str, str],
    demo_story: tuple[str, str],
) -> dict:
    """Build the client-safe operating layer for an industry preset.

    Industry presets must change the owner's starting workflow, not only colours
    and nouns. Keeping the bilingual values together also prevents one admin
    surface from drifting away from the public registration experience.
    """

    return {
        "starterCourses": [{"en": en, "zh": zh} for en, zh in courses],
        "registrationFocus": {"en": registration_focus[0], "zh": registration_focus[1]},
        "reportFocus": {"en": report_focus[0], "zh": report_focus[1]},
        "demoStory": {"en": demo_story[0], "zh": demo_story[1]},
    }


INDUSTRY_OPERATIONAL_TEMPLATES: dict[str, dict] = {
    "art": _operational_template(
        [("Foundation Art Lab", "基础艺术实验室"), ("Portfolio Studio", "作品集工作室"), ("Holiday Art Workshop", "假期艺术工作坊")],
        ("Medium, experience and creative goals", "媒介偏好、创作经验与目标"),
        ("Portfolio progress, attendance and credit runway", "作品进度、出勤与剩余课时"),
        ("Enquiry to trial, enrolment, class check-in and a parent-visible artwork", "从咨询、体验、报名、签到到家长可见作品"),
    ),
    "music": _operational_template(
        [("Piano Foundations", "钢琴基础"), ("AMEB Preparation", "AMEB 考级准备"), ("Student Recital Lab", "学员音乐会排练")],
        ("Instrument, grade and practice goals", "乐器、等级与练习目标"),
        ("Lesson continuity, repertoire and exam milestones", "连续上课、曲目与考级里程碑"),
        ("Trial lesson to recurring tuition, practice note and recital milestone", "从体验课到固定课、练习反馈与演出里程碑"),
    ),
    "math": _operational_template(
        [("Primary Foundations", "小学基础"), ("Secondary Problem Solving", "中学解题"), ("VCE Exam Clinic", "VCE 考试强化")],
        ("Year level, topic gaps and assessment dates", "年级、知识缺口与考试日期"),
        ("Attendance, topic coverage and renewal risk", "出勤、知识覆盖与续费风险"),
        ("Diagnostic enquiry to matched class, attendance and progress review", "从诊断咨询到匹配班级、出勤与阶段回顾"),
    ),
    "dance": _operational_template(
        [("Junior Ballet", "少儿芭蕾"), ("Jazz Technique", "爵士技巧"), ("Performance Company", "舞台表演团")],
        ("Age, style, level and performance goal", "年龄、舞种、水平与演出目标"),
        ("Roster capacity, attendance and performance readiness", "班级容量、出勤与演出准备度"),
        ("Trial class to troupe placement, rehearsal attendance and showcase media", "从体验课到分班、排练出勤与汇演影像"),
    ),
    "language": _operational_template(
        [("Everyday Conversation", "日常会话"), ("School Language Support", "校内语言辅导"), ("Exam Speaking Lab", "口语考试训练")],
        ("Target language, level and real-life use", "目标语言、水平与真实使用场景"),
        ("Attendance, level progression and speaking evidence", "出勤、等级进展与口语成果"),
        ("Placement enquiry to small group, speaking task and family update", "从水平咨询到小班、口语任务与家庭反馈"),
    ),
    "sports": _operational_template(
        [("Junior Skills", "少儿技能课"), ("Squad Training", "队伍训练"), ("Competition Clinic", "赛前强化")],
        ("Sport, level, health notes and competition goal", "项目、水平、健康备注与比赛目标"),
        ("Capacity, attendance and coaching milestones", "容量、出勤与训练里程碑"),
        ("Assessment to squad placement, session record and coaching feedback", "从评估到分队、训练记录与教练反馈"),
    ),
    "game": _operational_template(
        [("Minecraft Makers", "Minecraft 创造营"), ("Roblox Coding Lab", "Roblox 编程实验室"), ("Strategy Club", "策略俱乐部")],
        ("Platform, experience and learning objective", "平台、经验与学习目标"),
        ("Project completion, attendance and collaboration", "项目完成度、出勤与协作表现"),
        ("Interest enquiry to project cohort, attendance and shareable project", "从兴趣咨询到项目小组、出勤与可分享项目"),
    ),
    "general": _operational_template(
        [("Foundation Program", "基础课程"), ("Skills Development", "技能进阶"), ("Holiday Workshop", "假期工作坊")],
        ("Interests, experience and learning goals", "兴趣、经验与学习目标"),
        ("Enquiry conversion, attendance and credit runway", "咨询转化、出勤与剩余课时"),
        ("Enquiry to trial, enrolment, attendance and family progress update", "从咨询、体验、报名、出勤到家庭进度反馈"),
    ),
}

# Industry copy and visual design are now independent for real. This loop used
# to say the same thing in a comment and then weld them together on the very
# next line, which is how applying an industry silently repainted the site.
# Every industry gets the one palette; what it actually brings is the words and
# the operating template.
for _industry_key in INDUSTRY_PRESETS:
    INDUSTRY_PRESETS[_industry_key]["recommended_style_id"] = DEFAULT_STYLE_ID
    INDUSTRY_PRESETS[_industry_key]["theme"] = style_theme(DEFAULT_STYLE_ID)
    INDUSTRY_PRESETS[_industry_key]["operational_template"] = INDUSTRY_OPERATIONAL_TEMPLATES[_industry_key]

# The industry card in Studio Admin shows `slogan`; the site it publishes shows
# `hero.title`. Those were two hand-written strings, and in Chinese five of the
# eight had drifted apart — an owner picked 艺术 because the card promised
# 「大胆创作，让成长看得见。」 and the site went live saying
# 「让创意被看见，让成长有作品。」. In English they happened to be identical, so
# the fork was invisible to anyone reading the source in English.
#
# The hero title is now derived rather than written, so a card and the page it
# describes cannot disagree again. The subtitle stays hand-written: it is a
# different sentence doing a different job.
for _preset in INDUSTRY_PRESETS.values():
    _preset["hero"]["title"] = {"zh": _preset["slogan_zh"], "en": _preset["slogan"]}


def public_industry_presets() -> dict[str, dict]:
    """Return the client-safe preset shape used by both admin surfaces."""

    result: dict[str, dict] = {}
    for key, preset in INDUSTRY_PRESETS.items():
        result[key] = {
            "label": preset["label"],
            "labelZh": preset["label_zh"],
            "layout": preset["layout"],
            "slogan": preset["slogan"],
            "sloganZh": preset["slogan_zh"],
            "recommendedStyleId": preset["recommended_style_id"],
            "portalLabel": preset["copy_pack"]["portal_label"],
            "registerIntro": preset["copy_pack"]["register_intro"],
            "registerIntroZh": preset["register_intro_zh"],
            "registrationTitle": preset["registration_title"],
            "registrationTitleZh": preset["registration_title_zh"],
            # The public pages substitute these into %VENUE% / %WORK% / %WORKS%.
            # Without them the shared template calls every tenant a 画室 with
            # 作品, which is wrong for the piano, dance and game studios.
            "venueNoun": dict(preset["venue_noun"]),
            "workNoun": dict(preset["work_noun"]),
            "localizedCopy": {
                "hero_title": preset["hero"]["title"],
                "hero_subtitle": preset["hero"]["subtitle"],
                "primary_cta": {"zh": "预约体验", "en": "Book a Trial"},
                "secondary_cta": {"zh": "查看课程", "en": "Explore Programs"},
                "registration_title": {"zh": preset["registration_title_zh"], "en": preset["registration_title"]},
                "registration_intro": {"zh": preset["register_intro_zh"], "en": preset["copy_pack"]["register_intro"]},
                **INDUSTRY_SECTION_COPY.get(key, INDUSTRY_SECTION_COPY["general"]),
            },
            "visualTheme": dict(preset["theme"]),
            "registrationProfile": {"title": preset["registration_title"], "fields": [dict(field) for field in preset["fields"]]},
            "operationalTemplate": dict(preset["operational_template"]),
        }
    return result


def public_visual_style_presets() -> dict[str, dict]:
    """Return curated, client-safe visual styles with both scheme variants."""

    result: dict[str, dict] = {}
    for key, preset in VISUAL_STYLE_PRESETS.items():
        result[key] = {
            "label": preset["label"],
            "labelZh": preset["label_zh"],
            # 2-2: both languages ship, so the panel is not left translating an
            # English sentence through the admin dictionary at render time.
            "description": preset["description"],
            "descriptionZh": preset["description_zh"],
            "mood": preset["mood"],
            "harmony": preset["harmony"],
            "harmonyLabel": harmony_label(preset["harmony"]),
            "modes": list(preset["modes"]),
            # The editor needs both variants so it can preview a scheme switch
            # without another round trip.
            "schemes": {mode: style_theme(key, mode) for mode in preset["modes"]},
            "visualTheme": style_theme(key, preset["modes"][0]),
        }
    return result
