"""Single source of truth for industry onboarding and public-site presets."""

from __future__ import annotations

from . import palette


# ── Visual style presets ─────────────────────────────────────────────────────
#
# GENERATED by `python3 docs/design/palette_gen.py --emit-presets`. Do not edit
# a hex here; change the theme in `docs/studiosaas/palette.py` and re-emit.
# `backend/tests/test_theme_layering.py` fails on any drift.
#
# EIGHT NAMED THEMES, plus a free "custom" knob. There were eight until
# 2026-08-06, when they were collapsed to one because the PAPER carried the
# industry hue and whichever semantic role shared that hue stopped being
# visible — five of the seven light themes had one. That fix was real and it
# is still here (see `CHROMA_FLOOR` / `CHROMA_FLOOR_NEAR` / the chroma-derived
# neutral ramp in `palette.py`), but removing the eight identities was not
# required to ship it, and an owner opening Studio Admin the next day reported
# exactly that loss: "选择颜色主题" over a single empty swatch, with the
# right-hand preview showing the same fixed description for every industry.
#
# 2026-08-06 (second pass) restores the eight, with the actual defect fixed at
# its actual cause — every one of the 1080 assertions across these nine
# theme-modes passes with the ORIGINAL hues from before the collapse, because
# the generator itself is what got stronger, not the input it was given.
#
# Industry no longer AUTO-APPLIES a theme. `product-home.html:651` says
# "Templates change the vocabulary and the forms, not just the colours" — an
# industry still RECOMMENDS one (`INDUSTRY_STYLE_RECOMMENDATIONS` below, shown
# as a badge in the picker), but Studio Admin no longer writes that theme into
# a draft just because an industry card was clicked. That wiring, not the
# eight-theme system, was the actual defect.
#
# "custom" is the ninth entry: a studio whose brand hue matches none of the
# eight, usually because it has a logo. Only its HUE is taken from the input —
# lightness and saturation stay solved — so a fluorescent logo becomes a
# proper deep colour rather than a button nobody can read. See
# `accent_hue_from` in palette.py and `Design_Constraints.md` section 1.4.
#
#     python3 docs/design/palette_gen.py            # verify
#     python3 docs/design/palette_gen.py --table    # inspect

VISUAL_STYLE_PRESETS: dict[str, dict] = {
    "atelier-clay": {
        "label": "Atelier Clay", "label_zh": "陶土工坊",
        "description": "Warm clay on a paper surface, the way a gallery wall behaves — for studios where the work should lead.",
        "description_zh": "陶土的暖调落在纸质表面，像画廊的墙。适合让作品自己说话的工作室。",
        "mood": "warm, tactile, gallery",
        "harmony": "split-complementary",
        "modes": ['light', 'dark'],
        "themes": {
            "light": {
                "color_scheme": "light", "background_color": "#F3ECEA", "background_alt_color": "#EADFDB",
                "panel_color": "#FDFDFD", "surface_hover_color": "#F7F6F6", "text_color": "#211B19",
                "text_soft_color": "#473D3A", "muted_text_color": "#6E605C", "border_color": "#E0D4CF",
                "border_strong_color": "#917A72", "accent_color": "#955037", "accent_text_color": "#FFFFFF",
                "accent_muted_text_color": "#E4E0DF", "accent_hover_color": "#7F442F", "accent_pressed_color": "#683826",
                "accent_soft_color": "#E2CBC2", "accent_on_soft_color": "#874832", "accent_border_color": "#CAA598",
                "secondary_accent_color": "#3F6B61", "secondary_soft_color": "#D5EBE6", "secondary_on_soft_color": "#3F6B61",
                "secondary_border_color": "#AAC6C0", "success_color": "#2E7755", "success_soft_color": "#D5ECE1",
                "success_on_soft_color": "#2D7453", "success_border_color": "#A4C9B8", "warning_color": "#5D4119",
                "warning_soft_color": "#EFE5D9", "warning_on_soft_color": "#5D4119", "warning_border_color": "#CDBEAC",
                "danger_color": "#792E26", "danger_soft_color": "#FDE0DD", "danger_on_soft_color": "#792E26",
                "danger_border_color": "#DFB7B3", "info_color": "#3C6CA3", "info_soft_color": "#DDE8F3",
                "info_on_soft_color": "#3B6AA0", "info_border_color": "#AEC3DB", "focus_ring_color": "#BA6445",
                "disabled_surface_color": "#E6D9D5", "disabled_text_color": "#867A76", "scrim_color": "rgba(0,0,0,0.5)",
            },
            "dark": {
                "color_scheme": "dark", "background_color": "#150F0D", "background_alt_color": "#201715",
                "panel_color": "#2F241F", "surface_hover_color": "#332924", "text_color": "#E0DCDA",
                "text_soft_color": "#C3BCB9", "muted_text_color": "#988C87", "border_color": "#4A3D38",
                "border_strong_color": "#806C65", "accent_color": "#CE9985", "accent_text_color": "#14110F",
                "accent_muted_text_color": "#403836", "accent_hover_color": "#D8AE9E", "accent_pressed_color": "#E2C4B8",
                "accent_soft_color": "#563E34", "accent_on_soft_color": "#D4A594", "accent_border_color": "#745448",
                "secondary_accent_color": "#75AB9E", "secondary_soft_color": "#233933", "secondary_on_soft_color": "#75AB9E",
                "secondary_border_color": "#35534B", "success_color": "#368C64", "success_soft_color": "#233A2F",
                "success_on_soft_color": "#44B07D", "success_border_color": "#295641", "warning_color": "#A4742B",
                "warning_soft_color": "#433121", "warning_on_soft_color": "#CB913A", "warning_border_color": "#644724",
                "danger_color": "#C85D51", "danger_soft_color": "#492E27", "danger_on_soft_color": "#D6887F",
                "danger_border_color": "#743E35", "info_color": "#4C81BD", "info_soft_color": "#2B3641",
                "info_on_soft_color": "#77A0CD", "info_border_color": "#364F6A", "focus_ring_color": "#AE5E40",
                "disabled_surface_color": "#291E1B", "disabled_text_color": "#736865", "scrim_color": "rgba(0,0,0,0.66)",
            },
        },
    },
    "vintage-press": {
        "label": "Vintage Press", "label_zh": "复古印刷",
        "description": "The ink-and-paper restraint of an old print shop, for studios whose credibility rests on words and experience.",
        "description_zh": "老式印刷的墨与纸，克制的暖棕。适合靠文字与经验建立信任的工作室。",
        "mood": "editorial, cultured",
        "harmony": "split-complementary",
        "modes": ['light', 'dark'],
        "themes": {
            "light": {
                "color_scheme": "light", "background_color": "#F3EFEA", "background_alt_color": "#EAE3DB",
                "panel_color": "#FDFDFD", "surface_hover_color": "#F7F6F6", "text_color": "#221E1A",
                "text_soft_color": "#46403A", "muted_text_color": "#6C635A", "border_color": "#E0D8CF",
                "border_strong_color": "#8D7F70", "accent_color": "#835D33", "accent_text_color": "#FFFFFF",
                "accent_muted_text_color": "#E6E4E1", "accent_hover_color": "#6D4D2A", "accent_pressed_color": "#573E22",
                "accent_soft_color": "#DDCDBD", "accent_on_soft_color": "#74522D", "accent_border_color": "#C0A991",
                "secondary_accent_color": "#4C6877", "secondary_soft_color": "#DAE9F0", "secondary_on_soft_color": "#4C6877",
                "secondary_border_color": "#B1C4CD", "success_color": "#2F7856", "success_soft_color": "#D5ECE1",
                "success_on_soft_color": "#2E7453", "success_border_color": "#A4C9B8", "warning_color": "#5F4319",
                "warning_soft_color": "#F2E5D2", "warning_on_soft_color": "#5F4319", "warning_border_color": "#CFBFA7",
                "danger_color": "#7B2F27", "danger_soft_color": "#F6E2E0", "danger_on_soft_color": "#7B2F27",
                "danger_border_color": "#DAB9B6", "info_color": "#3D6DA5", "info_soft_color": "#DDE8F3",
                "info_on_soft_color": "#3B6AA0", "info_border_color": "#AEC3DC", "focus_ring_color": "#A3743F",
                "disabled_surface_color": "#E6DED5", "disabled_text_color": "#857E76", "scrim_color": "rgba(0,0,0,0.5)",
            },
            "dark": {
                "color_scheme": "dark", "background_color": "#15120D", "background_alt_color": "#1F1A15",
                "panel_color": "#2E271F", "surface_hover_color": "#322C24", "text_color": "#E1DFDC",
                "text_soft_color": "#C3BFBA", "muted_text_color": "#968F86", "border_color": "#4A4238",
                "border_strong_color": "#7C7062", "accent_color": "#C49F74", "accent_text_color": "#14120F",
                "accent_muted_text_color": "#3E3935", "accent_hover_color": "#CFB08D", "accent_pressed_color": "#D9C2A6",
                "accent_soft_color": "#514231", "accent_on_soft_color": "#CCAC86", "accent_border_color": "#6D5941",
                "secondary_accent_color": "#8AA5B2", "secondary_soft_color": "#2A3940", "secondary_on_soft_color": "#8AA5B2",
                "secondary_border_color": "#40525A", "success_color": "#378E65", "success_soft_color": "#253B31",
                "success_on_soft_color": "#45B27E", "success_border_color": "#2B5742", "warning_color": "#A5752C",
                "warning_soft_color": "#423421", "warning_on_soft_color": "#CC943E", "warning_border_color": "#634A25",
                "danger_color": "#C85E52", "danger_soft_color": "#493128", "danger_on_soft_color": "#D78B82",
                "danger_border_color": "#754036", "info_color": "#4C81BD", "info_soft_color": "#2D3843",
                "info_on_soft_color": "#7CA2CF", "info_border_color": "#37516C", "focus_ring_color": "#986D3B",
                "disabled_surface_color": "#28221B", "disabled_text_color": "#726C64", "scrim_color": "rgba(0,0,0,0.66)",
            },
        },
    },
    "studio-ink": {
        "label": "Studio Ink", "label_zh": "黑白纸墨",
        "description": "Near-monochrome ink on paper, with a single slate-blue note marking what can be clicked.",
        "description_zh": "近乎黑白的纸与墨，只用一抹石板蓝标出可点击之处，内容始终是主角。",
        "mood": "timeless, content-led",
        "harmony": "neutral / monochrome",
        "modes": ['light', 'dark'],
        "themes": {
            "light": {
                "color_scheme": "light", "background_color": "#EFEEEE", "background_alt_color": "#E3E2E2",
                "panel_color": "#FDFDFD", "surface_hover_color": "#F7F6F6", "text_color": "#1E1D1D",
                "text_soft_color": "#404040", "muted_text_color": "#646363", "border_color": "#D8D7D6",
                "border_strong_color": "#81807E", "accent_color": "#2C2A29", "accent_text_color": "#FFFFFF",
                "accent_muted_text_color": "#939292", "accent_hover_color": "#1C1B1A", "accent_pressed_color": "#0C0C0B",
                "accent_soft_color": "#E1CBC1", "accent_on_soft_color": "#2C2A29", "accent_border_color": "#BBA9A1",
                "secondary_accent_color": "#545F6F", "secondary_soft_color": "#DEE7F5", "secondary_on_soft_color": "#545F6F",
                "secondary_border_color": "#B8C1D0", "success_color": "#2F7856", "success_soft_color": "#D5ECE1",
                "success_on_soft_color": "#2E7453", "success_border_color": "#A4C9B8", "warning_color": "#8C6325",
                "warning_soft_color": "#EEE5D8", "warning_on_soft_color": "#876024", "warning_border_color": "#D1BEA3",
                "danger_color": "#B6463A", "danger_soft_color": "#FDE0DD", "danger_on_soft_color": "#B04438",
                "danger_border_color": "#E9B4AF", "info_color": "#3C6CA3", "info_soft_color": "#DDE8F3",
                "info_on_soft_color": "#3B6AA0", "info_border_color": "#AEC3DB", "focus_ring_color": "#7F7C7A",
                "disabled_surface_color": "#DEDDDD", "disabled_text_color": "#7E7D7D", "scrim_color": "rgba(0,0,0,0.5)",
            },
            "dark": {
                "color_scheme": "dark", "background_color": "#121111", "background_alt_color": "#1A1A1A",
                "panel_color": "#282727", "surface_hover_color": "#2C2C2B", "text_color": "#DEDEDD",
                "text_soft_color": "#BEBEBD", "muted_text_color": "#8F8F8E", "border_color": "#414141",
                "border_strong_color": "#727170", "accent_color": "#B8B3AE", "accent_text_color": "#121212",
                "accent_muted_text_color": "#454545", "accent_hover_color": "#C9C5C1", "accent_pressed_color": "#D9D7D4",
                "accent_soft_color": "#4D4237", "accent_on_soft_color": "#B8B3AE", "accent_border_color": "#645A50",
                "secondary_accent_color": "#8F9BAB", "secondary_soft_color": "#2D3643", "secondary_on_soft_color": "#939EAE",
                "secondary_border_color": "#454E5C", "success_color": "#378D65", "success_soft_color": "#243A2F",
                "success_on_soft_color": "#44B07E", "success_border_color": "#2A5641", "warning_color": "#A5752C",
                "warning_soft_color": "#3D3527", "warning_on_soft_color": "#CC943E", "warning_border_color": "#604B29",
                "danger_color": "#C85D51", "danger_soft_color": "#4B2E2B", "danger_on_soft_color": "#D78980",
                "danger_border_color": "#753E38", "info_color": "#4C81BD", "info_soft_color": "#2C3742",
                "info_on_soft_color": "#79A1CE", "info_border_color": "#37506B", "focus_ring_color": "#767472",
                "disabled_surface_color": "#222222", "disabled_text_color": "#6C6C6B", "scrim_color": "rgba(0,0,0,0.66)",
            },
        },
    },
    "harbour-calm": {
        "label": "Harbour Calm", "label_zh": "静谧海港",
        "description": "Still-water blues in adjacent hues — clear, trustworthy, and quiet enough to read all day.",
        "description_zh": "静水一般的蓝，色相彼此相邻。清楚、可信，长时间阅读也不吵。",
        "mood": "clear, trustworthy",
        "harmony": "analogous",
        "modes": ['light', 'dark'],
        "themes": {
            "light": {
                "color_scheme": "light", "background_color": "#E9EFF3", "background_alt_color": "#DAE4EB",
                "panel_color": "#FDFDFD", "surface_hover_color": "#F6F6F7", "text_color": "#191E22",
                "text_soft_color": "#394148", "muted_text_color": "#59656E", "border_color": "#CED9E1",
                "border_strong_color": "#6F8391", "accent_color": "#2E6892", "accent_text_color": "#FFFFFF",
                "accent_muted_text_color": "#DFE3E5", "accent_hover_color": "#27577B", "accent_pressed_color": "#1F4763",
                "accent_soft_color": "#C0D2E0", "accent_on_soft_color": "#295D83", "accent_border_color": "#92B0C7",
                "secondary_accent_color": "#2B6E64", "secondary_soft_color": "#D5EBE8", "secondary_on_soft_color": "#2B6E64",
                "secondary_border_color": "#A5C7C3", "success_color": "#2E7855", "success_soft_color": "#D5ECE1",
                "success_on_soft_color": "#2D7453", "success_border_color": "#A3C9B7", "warning_color": "#8C6325",
                "warning_soft_color": "#EEE5D8", "warning_on_soft_color": "#876024", "warning_border_color": "#D1BEA3",
                "danger_color": "#B6463A", "danger_soft_color": "#F6E2E0", "danger_on_soft_color": "#B04438",
                "danger_border_color": "#E4B6B2", "info_color": "#28486D", "info_soft_color": "#DAE8FA",
                "info_on_soft_color": "#28486D", "info_border_color": "#B0C3D9", "focus_ring_color": "#3A82B7",
                "disabled_surface_color": "#D3DFE7", "disabled_text_color": "#757F87", "scrim_color": "rgba(0,0,0,0.5)",
            },
            "dark": {
                "color_scheme": "dark", "background_color": "#0D1216", "background_alt_color": "#141B20",
                "panel_color": "#1E2930", "surface_hover_color": "#232E34", "text_color": "#DBDFE1",
                "text_soft_color": "#B9C0C4", "muted_text_color": "#869198", "border_color": "#37434B",
                "border_strong_color": "#627480", "accent_color": "#77ABCF", "accent_text_color": "#0F1215",
                "accent_muted_text_color": "#353B3F", "accent_hover_color": "#91BBD8", "accent_pressed_color": "#ACCCE2",
                "accent_soft_color": "#324754", "accent_on_soft_color": "#8AB6D6", "accent_border_color": "#436072",
                "secondary_accent_color": "#4BB1A1", "secondary_soft_color": "#233A3E", "secondary_on_soft_color": "#4BB1A1",
                "secondary_border_color": "#2C5554", "success_color": "#378D65", "success_soft_color": "#223A39",
                "success_on_soft_color": "#45B17E", "success_border_color": "#295648", "warning_color": "#A5752C",
                "warning_soft_color": "#3D3527", "warning_on_soft_color": "#CC943E", "warning_border_color": "#604B29",
                "danger_color": "#C85D51", "danger_soft_color": "#45312F", "danger_on_soft_color": "#D78A81",
                "danger_border_color": "#73403B", "info_color": "#4C81BD", "info_soft_color": "#263847",
                "info_on_soft_color": "#7AA2CE", "info_border_color": "#33516F", "focus_ring_color": "#367AAB",
                "disabled_surface_color": "#1A2329", "disabled_text_color": "#636D73", "scrim_color": "rgba(0,0,0,0.66)",
            },
        },
    },
    "cedar-grove": {
        "label": "Cedar Grove", "label_zh": "雪松林",
        "description": "Cedar green against ochre in a triadic balance — the palette of the outdoors and the training ground.",
        "description_zh": "雪松绿配赭石黄，三分色的平衡。属于户外与训练场的配色。",
        "mood": "grounded, healthy, active",
        "harmony": "triadic",
        "modes": ['light', 'dark'],
        "themes": {
            "light": {
                "color_scheme": "light", "background_color": "#EBF2EE", "background_alt_color": "#DDE8E2",
                "panel_color": "#FDFDFD", "surface_hover_color": "#F6F6F6", "text_color": "#1B211E",
                "text_soft_color": "#3B443F", "muted_text_color": "#5B6861", "border_color": "#D1DED7",
                "border_strong_color": "#71877C", "accent_color": "#377052", "accent_text_color": "#FFFFFF",
                "accent_muted_text_color": "#E2E6E4", "accent_hover_color": "#2D5B43", "accent_pressed_color": "#234734",
                "accent_soft_color": "#B7D7C7", "accent_on_soft_color": "#316349", "accent_border_color": "#8DB6A1",
                "secondary_accent_color": "#885C30", "secondary_soft_color": "#F0E5D9", "secondary_on_soft_color": "#885C30",
                "secondary_border_color": "#D2BDA8", "success_color": "#1F513A", "success_soft_color": "#CEEEDF",
                "success_on_soft_color": "#1F513A", "success_border_color": "#A5C9B9", "warning_color": "#8E6426",
                "warning_soft_color": "#EEE5D8", "warning_on_soft_color": "#885F24", "warning_border_color": "#D1BEA3",
                "danger_color": "#B8473A", "danger_soft_color": "#F6E2E0", "danger_on_soft_color": "#B04438",
                "danger_border_color": "#E4B6B1", "info_color": "#3D6DA5", "info_soft_color": "#DDE8F3",
                "info_on_soft_color": "#3B6AA0", "info_border_color": "#AEC3DC", "focus_ring_color": "#458C66",
                "disabled_surface_color": "#D7E4DD", "disabled_text_color": "#78837D", "scrim_color": "rgba(0,0,0,0.5)",
            },
            "dark": {
                "color_scheme": "dark", "background_color": "#0E1411", "background_alt_color": "#161E1A",
                "panel_color": "#212D26", "surface_hover_color": "#26312B", "text_color": "#DFE3E1",
                "text_soft_color": "#BDC4C0", "muted_text_color": "#89958E", "border_color": "#3A4841",
                "border_strong_color": "#65796E", "accent_color": "#6FB48F", "accent_text_color": "#101412",
                "accent_muted_text_color": "#363C39", "accent_hover_color": "#86C0A1", "accent_pressed_color": "#9ECCB4",
                "accent_soft_color": "#2D4D3C", "accent_on_soft_color": "#87C0A1", "accent_border_color": "#3D6751",
                "secondary_accent_color": "#C6996B", "secondary_soft_color": "#42362B", "secondary_on_soft_color": "#C6996B",
                "secondary_border_color": "#604D3A", "success_color": "#378E65", "success_soft_color": "#1F3F30",
                "success_on_soft_color": "#46B580", "success_border_color": "#275A42", "warning_color": "#A6752C",
                "warning_soft_color": "#403729", "warning_on_soft_color": "#CE9744", "warning_border_color": "#634D2A",
                "danger_color": "#C95E52", "danger_soft_color": "#473431", "danger_on_soft_color": "#D98E85",
                "danger_border_color": "#75433D", "info_color": "#4D81BD", "info_soft_color": "#293B40",
                "info_on_soft_color": "#7EA4CF", "info_border_color": "#36536B", "focus_ring_color": "#418461",
                "disabled_surface_color": "#1C2722", "disabled_text_color": "#66706A", "scrim_color": "rgba(0,0,0,0.66)",
            },
        },
    },
    "recital-plum": {
        "label": "Recital Plum", "label_zh": "独奏紫",
        "description": "Stage-curtain plum with a neighbouring violet, for recitals, graded exams and performance.",
        "description_zh": "舞台幕布般的紫，衬以邻近的蓝紫。适合演出、考级与表演路线。",
        "mood": "refined, performative",
        "harmony": "analogous",
        "modes": ['light', 'dark'],
        "themes": {
            "light": {
                "color_scheme": "light", "background_color": "#F0EBF2", "background_alt_color": "#E6DCE9",
                "panel_color": "#FDFDFD", "surface_hover_color": "#F6F6F7", "text_color": "#1D191F",
                "text_soft_color": "#443B46", "muted_text_color": "#695E6D", "border_color": "#DBD1DE",
                "border_strong_color": "#8A7890", "accent_color": "#89469D", "accent_text_color": "#FFFFFF",
                "accent_muted_text_color": "#E2DEE2", "accent_hover_color": "#773D88", "accent_pressed_color": "#643373",
                "accent_soft_color": "#E0C7E7", "accent_on_soft_color": "#7C408F", "accent_border_color": "#C59FD0",
                "secondary_accent_color": "#5656B7", "secondary_soft_color": "#E4E4FB", "secondary_on_soft_color": "#5656B7",
                "secondary_border_color": "#BCBCE8", "success_color": "#2E7654", "success_soft_color": "#D5ECE1",
                "success_on_soft_color": "#2D7453", "success_border_color": "#A4C9B8", "warning_color": "#8B6225",
                "warning_soft_color": "#EEE5D8", "warning_on_soft_color": "#876024", "warning_border_color": "#D1BEA3",
                "danger_color": "#B54539", "danger_soft_color": "#F6E2E0", "danger_on_soft_color": "#B14338",
                "danger_border_color": "#E4B6B2", "info_color": "#3C6CA3", "info_soft_color": "#DDE8F3",
                "info_on_soft_color": "#3B6AA0", "info_border_color": "#AEC3DB", "focus_ring_color": "#A360B8",
                "disabled_surface_color": "#E2D6E5", "disabled_text_color": "#827886", "scrim_color": "rgba(0,0,0,0.5)",
            },
            "dark": {
                "color_scheme": "dark", "background_color": "#130E15", "background_alt_color": "#1C151F",
                "panel_color": "#2B212E", "surface_hover_color": "#2F2632", "text_color": "#DCD9DD",
                "text_soft_color": "#BFB9C1", "muted_text_color": "#938996", "border_color": "#453A48",
                "border_strong_color": "#7A697F", "accent_color": "#C096CC", "accent_text_color": "#131014",
                "accent_muted_text_color": "#3E3740", "accent_hover_color": "#CEAED8", "accent_pressed_color": "#DDC6E3",
                "accent_soft_color": "#523859", "accent_on_soft_color": "#C6A0D1", "accent_border_color": "#6C4F75",
                "secondary_accent_color": "#9C9CD1", "secondary_soft_color": "#313147", "secondary_on_soft_color": "#9C9CD1",
                "secondary_border_color": "#494965", "success_color": "#368C64", "success_soft_color": "#22382E",
                "success_on_soft_color": "#43AE7C", "success_border_color": "#295440", "warning_color": "#A4742B",
                "warning_soft_color": "#3A3224", "warning_on_soft_color": "#CA8F35", "warning_border_color": "#5D4826",
                "danger_color": "#C85D51", "danger_soft_color": "#462C34", "danger_on_soft_color": "#D6867D",
                "danger_border_color": "#723C3E", "info_color": "#4C81BD", "info_soft_color": "#313147",
                "info_on_soft_color": "#749ECC", "info_border_color": "#3A4B6E", "focus_ring_color": "#9C55B2",
                "disabled_surface_color": "#241B28", "disabled_text_color": "#6E6671", "scrim_color": "rgba(0,0,0,0.66)",
            },
        },
    },
    "rehearsal-rose": {
        "label": "Rehearsal Rose", "label_zh": "排练玫瑰",
        "description": "Rehearsal-room rose against a moss green: kinetic without shouting.",
        "description_zh": "排练厅的玫红，配一抹苔绿。有动势，但不刺眼。",
        "mood": "expressive, warm, kinetic",
        "harmony": "split-complementary",
        "modes": ['light', 'dark'],
        "themes": {
            "light": {
                "color_scheme": "light", "background_color": "#F3EAED", "background_alt_color": "#EADBDF",
                "panel_color": "#FDFDFD", "surface_hover_color": "#F7F6F6", "text_color": "#20181A",
                "text_soft_color": "#473A3E", "muted_text_color": "#6E5D62", "border_color": "#E0CFD4",
                "border_strong_color": "#93767F", "accent_color": "#A23F5D", "accent_text_color": "#FFFFFF",
                "accent_muted_text_color": "#E2DEDF", "accent_hover_color": "#8C3650", "accent_pressed_color": "#762E44",
                "accent_soft_color": "#E8C7D1", "accent_on_soft_color": "#943A55", "accent_border_color": "#D39EAE",
                "secondary_accent_color": "#336D44", "secondary_soft_color": "#D6ECDD", "secondary_on_soft_color": "#336D44",
                "secondary_border_color": "#A8C8B2", "success_color": "#2E7654", "success_soft_color": "#D5ECE1",
                "success_on_soft_color": "#2D7453", "success_border_color": "#A4C9B8", "warning_color": "#8A6225",
                "warning_soft_color": "#EEE5D8", "warning_on_soft_color": "#876024", "warning_border_color": "#D1BEA3",
                "danger_color": "#762D25", "danger_soft_color": "#F6E2E0", "danger_on_soft_color": "#762D25",
                "danger_border_color": "#D9B9B6", "info_color": "#3C6CA3", "info_soft_color": "#DDE8F3",
                "info_on_soft_color": "#3B6AA0", "info_border_color": "#AEC3DB", "focus_ring_color": "#BE5978",
                "disabled_surface_color": "#E6D5D9", "disabled_text_color": "#87777C", "scrim_color": "rgba(0,0,0,0.5)",
            },
            "dark": {
                "color_scheme": "dark", "background_color": "#150D10", "background_alt_color": "#1F1518",
                "panel_color": "#302125", "surface_hover_color": "#342629", "text_color": "#DFD9DB",
                "text_soft_color": "#C2B9BC", "muted_text_color": "#98898E", "border_color": "#4A383E",
                "border_strong_color": "#836870", "accent_color": "#D193A5", "accent_text_color": "#140F11",
                "accent_muted_text_color": "#40373A", "accent_hover_color": "#DCACBA", "accent_pressed_color": "#E6C5CF",
                "accent_soft_color": "#593942", "accent_on_soft_color": "#D69FAF", "accent_border_color": "#764F5A",
                "secondary_accent_color": "#61B077", "secondary_soft_color": "#233929", "secondary_on_soft_color": "#61B077",
                "secondary_border_color": "#31543A", "success_color": "#368C64", "success_soft_color": "#22382E",
                "success_on_soft_color": "#43AE7C", "success_border_color": "#295440", "warning_color": "#A4742B",
                "warning_soft_color": "#432F26", "warning_on_soft_color": "#CA9036", "warning_border_color": "#634628",
                "danger_color": "#C85B4F", "danger_soft_color": "#4A2B2C", "danger_on_soft_color": "#D6867D",
                "danger_border_color": "#753B38", "info_color": "#4A7FBC", "info_soft_color": "#2A3540",
                "info_on_soft_color": "#779FCC", "info_border_color": "#354E69", "focus_ring_color": "#BA4E6E",
                "disabled_surface_color": "#281B1F", "disabled_text_color": "#736669", "scrim_color": "rgba(0,0,0,0.66)",
            },
        },
    },
    "arcade-lime": {
        "label": "Arcade Lime", "label_zh": "街机青柠",
        "description": "Arcade-screen lime, dark only: on a light page it turns olive and loses the reason it exists.",
        "description_zh": "街机屏幕上的荧光青柠，只做暗色——放到浅色底上会变成橄榄绿，失去存在的理由。",
        "mood": "digital, high energy",
        "harmony": "split-complementary",
        "modes": ['dark'],
        "themes": {
            "dark": {
                "color_scheme": "dark", "background_color": "#12180B", "background_alt_color": "#1B2311",
                "panel_color": "#26321A", "surface_hover_color": "#2B361F", "text_color": "#E6E9E4",
                "text_soft_color": "#C4C9BE", "muted_text_color": "#909B84", "border_color": "#424F33",
                "border_strong_color": "#6B7E56", "accent_color": "#75B926", "accent_text_color": "#12160E",
                "accent_muted_text_color": "#373E30", "accent_hover_color": "#88D42F", "accent_pressed_color": "#99DA4C",
                "accent_soft_color": "#38511D", "accent_on_soft_color": "#81CD2A", "accent_border_color": "#486C1F",
                "secondary_accent_color": "#AD97E2", "secondary_soft_color": "#3F3950", "secondary_on_soft_color": "#B09BE3",
                "secondary_border_color": "#584F72", "success_color": "#389067", "success_soft_color": "#294227",
                "success_on_soft_color": "#4AB985", "success_border_color": "#2E5E3E", "warning_color": "#A8772D",
                "warning_soft_color": "#3C3E1D", "warning_on_soft_color": "#D09C4E", "warning_border_color": "#635223",
                "danger_color": "#CA6256", "danger_soft_color": "#443B25", "danger_on_soft_color": "#DB938B",
                "danger_border_color": "#754937", "info_color": "#5285BF", "info_soft_color": "#323D48",
                "info_on_soft_color": "#84A9D2", "info_border_color": "#3D5670", "focus_ring_color": "#558918",
                "disabled_surface_color": "#232D16", "disabled_text_color": "#6C7660", "scrim_color": "rgba(0,0,0,0.66)",
            },
        },
    },
    "custom": {
        "label": "Custom", "label_zh": "自定义",
        "description": "Warm paper, near-black warm ink, and a single accent you set from your own logo.",
        "description_zh": "暖纸、近黑暖墨，和一支由你自己从 Logo 定下的强调色。",
        "mood": "set from your own logo",
        "harmony": "warm paper / your accent",
        "modes": ['light', 'dark'],
        "themes": {
            "light": {
                "color_scheme": "light", "background_color": "#F4F1EA", "background_alt_color": "#ECE7DA",
                "panel_color": "#FBF9F5", "surface_hover_color": "#F5F2EE", "text_color": "#221F1A",
                "text_soft_color": "#47423B", "muted_text_color": "#6C665B", "border_color": "#E1DBCE",
                "border_strong_color": "#8C826C", "accent_color": "#704B2E", "accent_text_color": "#FFFFFF",
                "accent_muted_text_color": "#CCC8C4", "accent_hover_color": "#5A3C25", "accent_pressed_color": "#452E1C",
                "accent_soft_color": "#DBC9BB", "accent_on_soft_color": "#704B2E", "accent_border_color": "#BDA593",
                "secondary_accent_color": "#576D49", "secondary_soft_color": "#DAE7D1", "secondary_on_soft_color": "#566B48",
                "secondary_border_color": "#B3C2A8", "success_color": "#307A57", "success_soft_color": "#D2E8DE",
                "success_on_soft_color": "#2D7151", "success_border_color": "#A1C6B5", "warning_color": "#8E6426",
                "warning_soft_color": "#EEE1CE", "warning_on_soft_color": "#855D24", "warning_border_color": "#D0BA9A",
                "danger_color": "#B9473B", "danger_soft_color": "#F2DFDA", "danger_on_soft_color": "#AD4237",
                "danger_border_color": "#E1B3AC", "info_color": "#3E6FA8", "info_soft_color": "#DAE4F0",
                "info_on_soft_color": "#3A679D", "info_border_color": "#AAC0DA", "focus_ring_color": "#AC7346",
                "disabled_surface_color": "#E9E3D3", "disabled_text_color": "#878178", "scrim_color": "rgba(0,0,0,0.5)",
            },
            "dark": {
                "color_scheme": "dark", "background_color": "#14120F", "background_alt_color": "#1E1B16",
                "panel_color": "#2C2921", "surface_hover_color": "#302E26", "text_color": "#E2E0DC",
                "text_soft_color": "#C4C0BA", "muted_text_color": "#979187", "border_color": "#47433B",
                "border_strong_color": "#787366", "accent_color": "#C69E7E", "accent_text_color": "#141210",
                "accent_muted_text_color": "#3E3A36", "accent_hover_color": "#D1B197", "accent_pressed_color": "#DCC3B0",
                "accent_soft_color": "#544234", "accent_on_soft_color": "#CEAC90", "accent_border_color": "#705946",
                "secondary_accent_color": "#90A880", "secondary_soft_color": "#2E3B25", "secondary_on_soft_color": "#90A880",
                "secondary_border_color": "#445439", "success_color": "#378E65", "success_soft_color": "#263C31",
                "success_on_soft_color": "#45B37F", "success_border_color": "#2C5842", "warning_color": "#A5752C",
                "warning_soft_color": "#423622", "warning_on_soft_color": "#CD9642", "warning_border_color": "#644C25",
                "danger_color": "#C85E52", "danger_soft_color": "#48322A", "danger_on_soft_color": "#D88C83",
                "danger_border_color": "#754138", "info_color": "#4C81BD", "info_soft_color": "#2E3844",
                "info_on_soft_color": "#7CA3CF", "info_border_color": "#38516D", "focus_ring_color": "#A06A41",
                "disabled_surface_color": "#27231C", "disabled_text_color": "#716C64", "scrim_color": "rgba(0,0,0,0.66)",
            },
        },
    },
}


# Each industry RECOMMENDS a theme (shown as a badge in the picker) — it does
# not choose one. Restored from before the 2026-08-06 collapse: music no
# longer inherits the warm-brown editorial palette, and language gets its own
# analogous set instead of sharing dance's.
INDUSTRY_STYLE_RECOMMENDATIONS = {
    "art": "atelier-clay", "music": "recital-plum", "math": "harbour-calm",
    "dance": "rehearsal-rose", "language": "harbour-calm", "sports": "cedar-grove",
    "game": "arcade-lime", "general": "vintage-press",
}

DEFAULT_STYLE_ID = "vintage-press"

# Shape is a presentation choice, not a palette choice, so it lives beside the
# theme rather than inside it — a studio can pick sharp buttons on any palette.
STYLE_SHAPE = {
    "atelier-clay":   {"button_style": "soft",    "font_mood": "serif"},
    "vintage-press":  {"button_style": "soft",    "font_mood": "serif"},
    "studio-ink":     {"button_style": "sharp",   "font_mood": "modern"},
    "harbour-calm":   {"button_style": "soft",    "font_mood": "modern"},
    "cedar-grove":    {"button_style": "soft",    "font_mood": "modern"},
    "recital-plum":   {"button_style": "rounded", "font_mood": "classic"},
    "rehearsal-rose": {"button_style": "rounded", "font_mood": "classic"},
    "arcade-lime":    {"button_style": "sharp",   "font_mood": "modern"},
    "custom":         {"button_style": "soft",    "font_mood": "serif"},
}

HARMONY_LABELS: dict[str, dict[str, str]] = {
    "split-complementary": {"zh": "分裂互补", "en": "Split-complementary"},
    "analogous": {"zh": "邻近色", "en": "Analogous"},
    "triadic": {"zh": "三分色", "en": "Triadic"},
    "neutral / monochrome": {"zh": "单色中性", "en": "Neutral / monochrome"},
    "warm paper / your accent": {"zh": "暖纸 · 你的强调色",
                                 "en": "Warm paper / your accent"},
}


def harmony_label(harmony: str) -> dict[str, str]:
    """Return the human-readable name of a colour relationship."""

    return dict(HARMONY_LABELS.get(harmony, {"zh": harmony, "en": harmony}))


# The one entry whose accent is a live tenant input rather than a curated
# design decision — see `studio_theme()`/`free_accent` in palette.py.
FREE_ACCENT_STYLE_ID = "custom"


def style_theme(style_id: str, scheme: str = "light", accent_hue: float | None = None) -> dict:
    """Return one style's flat token map for a given light/dark scheme.

    Falls back to the style's only available mode when the requested one does
    not exist, and to the default style when the id is unknown, so a stale
    tenant setting can never render an empty theme.

    `accent_hue` is honoured ONLY for `FREE_ACCENT_STYLE_ID` — that is the
    studio's one colour knob, solved rather than read from a literal, so a
    neon logo becomes a deep pine rather than a button nobody can read. For
    any of the eight curated themes the hue is part of the design and an
    `accent_hue` argument is ignored: the literal below is the whole point of
    a curated theme staying put.
    """

    preset = VISUAL_STYLE_PRESETS.get(style_id) or VISUAL_STYLE_PRESETS[DEFAULT_STYLE_ID]
    resolved_id = style_id if style_id in VISUAL_STYLE_PRESETS else DEFAULT_STYLE_ID
    themes = preset["themes"]
    mode = scheme if scheme in themes else preset["modes"][0]
    shape = {
        "style_id": resolved_id,
        "theme_mode": "preset",
        **STYLE_SHAPE.get(resolved_id, STYLE_SHAPE[DEFAULT_STYLE_ID]),
    }
    if accent_hue is None or resolved_id != FREE_ACCENT_STYLE_ID:
        return {**shape, **themes[mode]}
    solved = palette.build(palette.studio_theme(float(accent_hue)), mode == "dark")
    return {**shape, "accent_hue": round(float(accent_hue) % 360, 1), **solved}


def accent_hue_of_colour(value: str) -> float:
    """The hue this product will actually use for a studio-supplied colour."""

    return palette.accent_hue_from(value)


# B1: per-industry section copy. The template shipped one set of headings
# to every tenant, so five live studios all said 「总有一种，适合此刻的你」.
# A parent comparing two of them saw the same sentence twice.
INDUSTRY_SECTION_COPY: dict[str, dict] = {
    "art": {
        "courses_title": {"zh": "总有一种画法，适合此刻的你", "en": "There is a way of making that fits you now"},
        "courses_lead": {"zh": "从第一笔到完整作品，按你的节奏推进。", "en": "From a first mark to a finished piece, at your own pace."},
        "gallery_title": {"zh": "他们画出来的东西", "en": "What our students have made"},
        "gallery_lead": {"zh": "学员在这里完成的作品，经本人同意后展出。", "en": "Made here, shared with each student's consent."},
        "faq_title": {"zh": "动笔之前，先了解这些", "en": "Worth knowing before you start"},
    },
    "music": {
        "courses_title": {"zh": "总有一种节奏，适合此刻的你", "en": "There is a tempo that fits you now"},
        "courses_lead": {"zh": "从识谱到完整曲目，按你的节奏推进。", "en": "From reading notes to a finished piece, at your own pace."},
        "gallery_title": {"zh": "他们弹出来的声音", "en": "What our students have played"},
        "gallery_lead": {"zh": "学员的演奏与曲目记录，经本人同意后展出。", "en": "Recordings and repertoire, shared with each student's consent."},
        "faq_title": {"zh": "坐上琴凳之前，先了解这些", "en": "Worth knowing before the first lesson"},
    },
    "dance": {
        "courses_title": {"zh": "总有一支舞，适合此刻的你", "en": "There is a style that fits you now"},
        "courses_lead": {"zh": "从基本功到成套编排，按你的节奏推进。", "en": "From fundamentals to full choreography, at your own pace."},
        "gallery_title": {"zh": "他们跳出来的样子", "en": "What our dancers have performed"},
        "gallery_lead": {"zh": "课堂与演出的录像，经本人同意后展出。", "en": "Class and stage recordings, shared with each dancer's consent."},
        "faq_title": {"zh": "换上舞鞋之前，先了解这些", "en": "Worth knowing before the first class"},
    },
    "math": {
        "courses_title": {"zh": "总有一条路径，适合此刻的进度", "en": "There is a path that fits where you are now"},
        "courses_lead": {"zh": "先找准知识缺口，再按步骤补齐。", "en": "Find the gaps first, then close them step by step."},
        "gallery_title": {"zh": "他们的进步轨迹", "en": "How our learners have progressed"},
        "gallery_lead": {"zh": "阶段性练习与测评记录，经本人同意后展出。", "en": "Exercises and assessments, shared with each learner's consent."},
        "faq_title": {"zh": "开始补课之前，先了解这些", "en": "Worth knowing before you start"},
    },
    "language": {
        "courses_title": {"zh": "总有一种开口方式，适合此刻的你", "en": "There is a way in that fits you now"},
        "courses_lead": {"zh": "从日常表达到考试准备，按你的节奏推进。", "en": "From everyday conversation to exam prep, at your own pace."},
        "gallery_title": {"zh": "他们说出来的样子", "en": "How our learners are speaking now"},
        "gallery_lead": {"zh": "口语与作业记录，经本人同意后展出。", "en": "Speaking and coursework records, shared with each learner's consent."},
        "faq_title": {"zh": "开口之前，先了解这些", "en": "Worth knowing before you start"},
    },
    "sports": {
        "courses_title": {"zh": "总有一种训练，适合此刻的你", "en": "There is a programme that fits you now"},
        "courses_lead": {"zh": "从体能基础到比赛准备，按你的节奏推进。", "en": "From base fitness to competition, at your own pace."},
        "gallery_title": {"zh": "他们练出来的成绩", "en": "What our athletes have achieved"},
        "gallery_lead": {"zh": "训练与比赛记录，经本人同意后展出。", "en": "Training and competition records, shared with each athlete's consent."},
        "faq_title": {"zh": "开始训练之前，先了解这些", "en": "Worth knowing before your first session"},
    },
    "game": {
        "courses_title": {"zh": "总有一个方向，适合此刻的你", "en": "There is a track that fits you now"},
        "courses_lead": {"zh": "从上手到独立完成作品，按你的节奏推进。", "en": "From first build to shipping your own, at your own pace."},
        "gallery_title": {"zh": "他们做出来的东西", "en": "What our students have built"},
        "gallery_lead": {"zh": "学员完成的项目，经本人同意后展出。", "en": "Projects built here, shared with each student's consent."},
        "faq_title": {"zh": "开始之前，先了解这些", "en": "Worth knowing before you start"},
    },
    "general": {
        "courses_title": {"zh": "总有一种节奏，适合此刻的你", "en": "There is a pace that fits you now"},
        "courses_lead": {"zh": "从零基础到进阶，按你的节奏推进。", "en": "From first steps to advanced, at your own pace."},
        "gallery_title": {"zh": "他们完成的记录", "en": "What our students have made"},
        "gallery_lead": {"zh": "学员在这里完成的记录，经本人同意后展出。", "en": "Made here, shared with each student's consent."},
        "faq_title": {"zh": "开始之前，先了解这些", "en": "Worth knowing before you start"},
    },
}


def _field(
    key: str,
    label_en: str,
    label_zh: str,
    placeholder_en: str,
    placeholder_zh: str,
) -> dict:
    return {
        "key": key,
        "label": label_en,
        "label_en": label_en,
        "label_zh": label_zh,
        "placeholder": placeholder_en,
        "placeholder_en": placeholder_en,
        "placeholder_zh": placeholder_zh,
        "type": "text",
        "required": False,
        "options": [],
    }


INDUSTRY_PRESETS: dict[str, dict] = {
    "art": {
        "label": "Art",
        "label_zh": "艺术",
        "layout": "editorial",
        "slogan": "Create boldly. Grow visibly.", "slogan_zh": "大胆创作，让成长看得见。",
        # `title` is filled in below from the slogan — do not write it here.
        "hero": {
            "subtitle": {"zh": "从兴趣启发到系统表达，记录每一次真实成长。", "en": "From first ideas to confident expression, make every stage of growth visible."},
        },
        "venue_noun": {"zh": "画室", "en": "studio"},
        "work_noun": {"zh": "作品", "en": "work", "en_plural": "works"},
        "registration_title": "Tell us how they like to create",
        "registration_title_zh": "告诉我们学员喜欢怎样创作",
        "copy_pack": {"portal_label": "Art Student Portal", "register_intro": "Three questions about style, experience and goals, then the studio will suggest a class and a time."},
        "register_intro_zh": "三个关于创作形式、经验与目标的问题，之后画室会推荐合适的课程与时间。",
        "theme": {"background_color": "#FFF7F3", "panel_color": "#FFFFFF", "text_color": "#2B2118", "accent_color": "#A23E5C", "secondary_accent_color": "#6B4F3A", "button_style": "soft", "font_mood": "serif"},
        "fields": [
            _field("artStyle", "Preferred style", "喜欢的艺术形式", "Watercolour, sketching, acrylic", "水彩、素描、丙烯等"),
            _field("experience", "Current experience", "目前经验", "Beginner, some experience, portfolio prep", "零基础、有一定经验、作品集准备"),
            _field("goals", "Creative goals", "创作目标", "Relax, build technique, portfolio prep", "培养兴趣、提升技法、准备作品集"),
        ],
    },
    "music": {
        "label": "Music", "label_zh": "音乐", "layout": "performance",
        "slogan": "Find your rhythm. Make every practice count.", "slogan_zh": "找到自己的节奏，让每次练习都算数。",
        "hero": {"subtitle": {"zh": "清晰的目标、适合的节奏与看得见的音乐成长。", "en": "Clear goals, the right pace, and musical progress you can hear."}},
        "venue_noun": {"zh": "琴行", "en": "studio"},
        "work_noun": {"zh": "曲目", "en": "piece", "en_plural": "pieces"},
        "registration_title": "Tell us what they want to play", "registration_title_zh": "告诉我们学员想学什么乐器",
        "copy_pack": {"portal_label": "Music Student Portal", "register_intro": "The instrument, the current level and the goal, then the studio will match a teacher and a lesson time."},
        "register_intro_zh": "乐器、当前水平与音乐目标，之后琴行会匹配合适的老师与上课时间。",
        "theme": {"background_color": "#F7F5FF", "panel_color": "#FFFFFF", "text_color": "#201A35", "accent_color": "#5B3FA8", "secondary_accent_color": "#1F2A44", "button_style": "soft", "font_mood": "classic"},
        "fields": [
            _field("instrument", "Instrument", "乐器或声乐", "Piano, guitar, violin, voice", "钢琴、吉他、小提琴、声乐等"),
            _field("level", "Current level", "当前水平", "Beginner, AMEB Grade 2, self-taught", "零基础、考级程度、自学经验"),
            _field("goals", "Music goals", "音乐目标", "Exam prep, performance, confidence", "考级、演出、兴趣或自信表达"),
        ],
    },
    "math": {
        # `label` is display only — the category key stays "math". Australian
        # spelling, like the rest of the product's copy.
        "label": "Maths", "label_zh": "数学", "layout": "structured",
        "slogan": "Understand the method. Build lasting confidence.", "slogan_zh": "理解方法，建立长久的信心。",
        "hero": {"subtitle": {"zh": "找准知识缺口，用清晰方法建立可持续的学习能力。", "en": "Find the gaps, learn a clear method, and build skills that last."}},
        "venue_noun": {"zh": "教室", "en": "centre"},
        "work_noun": {"zh": "练习", "en": "exercise", "en_plural": "exercises"},
        "registration_title": "Tell us where they are and what is hard", "registration_title_zh": "告诉我们目前的学习阶段与难点",
        "copy_pack": {"portal_label": "Maths Student Portal", "register_intro": "Year level, the topics that are hard, and what you want to reach — the centre replies with a plan."},
        "register_intro_zh": "年级、当前难点与希望达到的目标，教室会给出对应的学习方案。",
        "theme": {"background_color": "#F3F7FF", "panel_color": "#FFFFFF", "text_color": "#172033", "accent_color": "#1D4ED8", "secondary_accent_color": "#0F766E", "button_style": "sharp", "font_mood": "modern"},
        "fields": [
            _field("yearLevel", "Year level", "年级", "Year 5, Year 9, VCE", "五年级、九年级、VCE 等"),
            _field("topics", "Topic focus", "重点内容", "Algebra, fractions, problem solving", "代数、分数、应用题等"),
            _field("goals", "Learning goals", "学习目标", "Catch up, extension, exam confidence", "补基础、拓展、考试信心"),
        ],
    },
    "dance": {
        "label": "Dance", "label_zh": "舞蹈", "layout": "expressive",
        "slogan": "Move with confidence. Grow through practice.", "slogan_zh": "自信地舞动，在训练中成长。",
        "hero": {"subtitle": {"zh": "兼顾技术、体态与舞台表达，让每一步更自信。", "en": "Build technique, presence, and confidence in every movement."}},
        "venue_noun": {"zh": "舞蹈教室", "en": "studio"},
        "work_noun": {"zh": "舞蹈录像", "en": "recording", "en_plural": "recordings"},
        "registration_title": "Tell us about the dancer", "registration_title_zh": "告诉我们舞者的经验与目标",
        "copy_pack": {"portal_label": "Dance Student Portal", "register_intro": "The style, the level and the goal, then the studio will suggest a class and a trial time."},
        "register_intro_zh": "舞种、当前水平与训练目标，之后舞蹈教室会安排合适的班级与试课时间。",
        "theme": {"background_color": "#FFF4F8", "panel_color": "#FFFFFF", "text_color": "#2D1723", "accent_color": "#B4236E", "secondary_accent_color": "#6D315E", "button_style": "rounded", "font_mood": "classic"},
        "fields": [
            _field("danceStyle", "Dance style", "喜欢的舞种", "Ballet, jazz, hip hop, contemporary", "芭蕾、爵士、街舞、现代舞等"),
            _field("level", "Current level", "当前水平", "Beginner, intermediate, exam stream", "零基础、中级、考级方向"),
            _field("goals", "Dance goals", "舞蹈目标", "Fitness, performance, technique", "体能、表演、技术提升"),
        ],
    },
    "language": {
        "label": "Language", "label_zh": "语言", "layout": "friendly",
        "slogan": "Find your voice. Connect with the world.", "slogan_zh": "开口表达，连接更大的世界。",
        "hero": {"subtitle": {"zh": "从真实沟通出发，建立能够长期使用的语言能力。", "en": "Build practical language skills through real communication."}},
        "venue_noun": {"zh": "教室", "en": "centre"},
        "work_noun": {"zh": "练习", "en": "exercise", "en_plural": "exercises"},
        "registration_title": "Tell us which language and what level", "registration_title_zh": "告诉我们学习语言与当前水平",
        "copy_pack": {"portal_label": "Language Student Portal", "register_intro": "Which language, what level, and where you will use it — the centre replies with a class and a time."},
        "register_intro_zh": "目标语言、当前水平与使用场景，教室会推荐合适的课程与上课时间。",
        "theme": {"background_color": "#F2FBFC", "panel_color": "#FFFFFF", "text_color": "#163036", "accent_color": "#0E7490", "secondary_accent_color": "#7C3AED", "button_style": "rounded", "font_mood": "modern"},
        "fields": [
            _field("language", "Language", "目标语言", "English, Mandarin, Japanese, French", "英语、中文、日语、法语等"),
            _field("level", "Current level", "当前水平", "Beginner, conversational, exam prep", "零基础、日常交流、考试准备"),
            _field("goals", "Language goals", "语言目标", "Speaking, school support, travel", "口语、学校辅导、旅行或工作"),
        ],
    },
    "sports": {
        "label": "Sports", "label_zh": "运动", "layout": "energetic",
        "slogan": "Train with purpose. Grow stronger every session.", "slogan_zh": "有目标地训练，一次比一次更强。",
        "hero": {"subtitle": {"zh": "科学训练、清晰反馈与持续进步。", "en": "Purposeful coaching, clear feedback, and steady progress."}},
        "venue_noun": {"zh": "训练中心", "en": "club"},
        "work_noun": {"zh": "训练记录", "en": "session record", "en_plural": "session records"},
        "registration_title": "Tell us the sport and the goal", "registration_title_zh": "告诉我们运动项目与训练目标",
        "copy_pack": {"portal_label": "Sports Student Portal", "register_intro": "The sport, the current level and the goal, then the club will suggest a squad and a session time."},
        "register_intro_zh": "运动项目、当前水平与训练目标，之后训练中心会推荐合适的组别与训练时间。",
        "theme": {"background_color": "#F4FAF5", "panel_color": "#FFFFFF", "text_color": "#17251A", "accent_color": "#166534", "secondary_accent_color": "#B45309", "button_style": "sharp", "font_mood": "modern"},
        "fields": [
            _field("sport", "Sport", "运动项目", "Tennis, swimming, basketball, soccer", "网球、游泳、篮球、足球等"),
            _field("level", "Current level", "当前水平", "Beginner, club, competition", "零基础、俱乐部、比赛级别"),
            _field("goals", "Training goals", "训练目标", "Fitness, technique, competition prep", "体能、技术、比赛准备"),
        ],
    },
    "game": {
        # "Game" dropped the half of the offer the Chinese label keeps: 编程.
        "label": "Games & Coding", "label_zh": "游戏与编程", "layout": "digital",
        "slogan": "Play, think, create, and level up.", "slogan_zh": "在玩中思考、创造与升级。",
        "hero": {"subtitle": {"zh": "把兴趣转化为策略、编程、创造力与团队能力。", "en": "Turn play into strategy, coding, creativity, and teamwork."}},
        "venue_noun": {"zh": "工作室", "en": "studio"},
        "work_noun": {"zh": "项目", "en": "project", "en_plural": "projects"},
        "registration_title": "Tell us what they want to build or play", "registration_title_zh": "告诉我们感兴趣的游戏或编程方向",
        "copy_pack": {"portal_label": "Games & Coding Portal", "register_intro": "What they want to build or play, how much they have done, and what they want to learn — the studio replies with a project and a start date."},
        "register_intro_zh": "想做什么或想玩什么、目前的经验与学习目标，之后工作室会推荐合适的项目与开课时间。",
        "theme": {"background_color": "#F6F4FF", "panel_color": "#FFFFFF", "text_color": "#1F1735", "accent_color": "#5B21B6", "secondary_accent_color": "#0F766E", "button_style": "rounded", "font_mood": "modern"},
        "fields": [
            _field("gameType", "Game or activity", "游戏或活动方向", "Roblox, Minecraft, chess, coding games", "Roblox、Minecraft、国际象棋、编程游戏"),
            _field("level", "Current level", "当前经验", "Beginner, casual, competitive", "零基础、兴趣玩家、竞赛方向"),
            _field("goals", "Learning goals", "学习目标", "Strategy, coding, teamwork, confidence", "策略、编程、团队合作、自信"),
        ],
    },
    "general": {
        "label": "General", "label_zh": "通用", "layout": "neutral",
        "slogan": "A learning path that fits every student.", "slogan_zh": "适合每个学员的成长路径。",
        "hero": {"subtitle": {"zh": "从兴趣和目标出发，在适合的节奏中稳步成长。", "en": "Start with the learner's interests and goals, then grow at the right pace."}},
        "venue_noun": {"zh": "工作室", "en": "studio"},
        "work_noun": {"zh": "作品", "en": "work", "en_plural": "works"},
        "registration_title": "Tell us about the student", "registration_title_zh": "告诉我们学员的兴趣与学习目标",
        "copy_pack": {"portal_label": "Student Portal", "register_intro": "Interests, experience and goals, then the studio will suggest a class and a time."},
        "register_intro_zh": "兴趣方向、当前经验与学习目标，之后工作室会推荐合适的课程与时间。",
        "theme": {"background_color": "#F8FAFC", "panel_color": "#FFFFFF", "text_color": "#1E293B", "accent_color": "#1E40AF", "secondary_accent_color": "#0F766E", "button_style": "soft", "font_mood": "modern"},
        "fields": [
            _field("interests", "Interests", "兴趣方向", "What does the student enjoy?", "学员平时喜欢什么？"),
            _field("experience", "Experience", "当前经验", "Beginner, some experience, advanced", "零基础、有一定经验、进阶"),
            _field("goals", "Goals", "学习目标", "Confidence, skills, exam prep, fun", "自信、技能、考试准备或兴趣"),
        ],
    },
}


def _operational_template(
    courses: list[tuple[str, str]],
    registration_focus: tuple[str, str],
    report_focus: tuple[str, str],
    demo_story: tuple[str, str],
) -> dict:
    """Build the client-safe operating layer for an industry preset.

    Industry presets must change the owner's starting workflow, not only colours
    and nouns. Keeping the bilingual values together also prevents one admin
    surface from drifting away from the public registration experience.
    """

    return {
        "starterCourses": [{"en": en, "zh": zh} for en, zh in courses],
        "registrationFocus": {"en": registration_focus[0], "zh": registration_focus[1]},
        "reportFocus": {"en": report_focus[0], "zh": report_focus[1]},
        "demoStory": {"en": demo_story[0], "zh": demo_story[1]},
    }


INDUSTRY_OPERATIONAL_TEMPLATES: dict[str, dict] = {
    "art": _operational_template(
        [("Foundation Art Lab", "基础艺术实验室"), ("Portfolio Studio", "作品集工作室"), ("Holiday Art Workshop", "假期艺术工作坊")],
        ("Medium, experience and creative goals", "媒介偏好、创作经验与目标"),
        ("Portfolio progress, attendance and credit runway", "作品进度、出勤与剩余课时"),
        ("Enquiry to trial, enrolment, class check-in and a parent-visible artwork", "从咨询、体验、报名、签到到家长可见作品"),
    ),
    "music": _operational_template(
        [("Piano Foundations", "钢琴基础"), ("AMEB Preparation", "AMEB 考级准备"), ("Student Recital Lab", "学员音乐会排练")],
        ("Instrument, grade and practice goals", "乐器、等级与练习目标"),
        ("Lesson continuity, repertoire and exam milestones", "连续上课、曲目与考级里程碑"),
        ("Trial lesson to recurring tuition, practice note and recital milestone", "从体验课到固定课、练习反馈与演出里程碑"),
    ),
    "math": _operational_template(
        [("Primary Foundations", "小学基础"), ("Secondary Problem Solving", "中学解题"), ("VCE Exam Clinic", "VCE 考试强化")],
        ("Year level, topic gaps and assessment dates", "年级、知识缺口与考试日期"),
        ("Attendance, topic coverage and renewal risk", "出勤、知识覆盖与续费风险"),
        ("Diagnostic enquiry to matched class, attendance and progress review", "从诊断咨询到匹配班级、出勤与阶段回顾"),
    ),
    "dance": _operational_template(
        [("Junior Ballet", "少儿芭蕾"), ("Jazz Technique", "爵士技巧"), ("Performance Company", "舞台表演团")],
        ("Age, style, level and performance goal", "年龄、舞种、水平与演出目标"),
        ("Roster capacity, attendance and performance readiness", "班级容量、出勤与演出准备度"),
        ("Trial class to troupe placement, rehearsal attendance and showcase media", "从体验课到分班、排练出勤与汇演影像"),
    ),
    "language": _operational_template(
        [("Everyday Conversation", "日常会话"), ("School Language Support", "校内语言辅导"), ("Exam Speaking Lab", "口语考试训练")],
        ("Target language, level and real-life use", "目标语言、水平与真实使用场景"),
        ("Attendance, level progression and speaking evidence", "出勤、等级进展与口语成果"),
        ("Placement enquiry to small group, speaking task and family update", "从水平咨询到小班、口语任务与家庭反馈"),
    ),
    "sports": _operational_template(
        [("Junior Skills", "少儿技能课"), ("Squad Training", "队伍训练"), ("Competition Clinic", "赛前强化")],
        ("Sport, level, health notes and competition goal", "项目、水平、健康备注与比赛目标"),
        ("Capacity, attendance and coaching milestones", "容量、出勤与训练里程碑"),
        ("Assessment to squad placement, session record and coaching feedback", "从评估到分队、训练记录与教练反馈"),
    ),
    "game": _operational_template(
        [("Minecraft Makers", "Minecraft 创造营"), ("Roblox Coding Lab", "Roblox 编程实验室"), ("Strategy Club", "策略俱乐部")],
        ("Platform, experience and learning objective", "平台、经验与学习目标"),
        ("Project completion, attendance and collaboration", "项目完成度、出勤与协作表现"),
        ("Interest enquiry to project cohort, attendance and shareable project", "从兴趣咨询到项目小组、出勤与可分享项目"),
    ),
    "general": _operational_template(
        [("Foundation Program", "基础课程"), ("Skills Development", "技能进阶"), ("Holiday Workshop", "假期工作坊")],
        ("Interests, experience and learning goals", "兴趣、经验与学习目标"),
        ("Enquiry conversion, attendance and credit runway", "咨询转化、出勤与剩余课时"),
        ("Enquiry to trial, enrolment, attendance and family progress update", "从咨询、体验、报名、出勤到家庭进度反馈"),
    ),
}

# Industry copy and visual design are independent. `recommended_style_id` is
# a BADGE the picker shows next to one theme — "推荐" — never a value written
# into a tenant's draft. The write used to happen right here, on the very next
# line after a comment promising it wouldn't, which is how selecting an
# industry silently repainted the whole site. Studio Admin's
# `applyCategoryPreset()` must apply copy/forms/template only and leave
# `visualTheme` untouched; this dict is what it reads the recommendation from
# to render the badge.
for _industry_key, _style_id in INDUSTRY_STYLE_RECOMMENDATIONS.items():
    INDUSTRY_PRESETS[_industry_key]["recommended_style_id"] = _style_id
    INDUSTRY_PRESETS[_industry_key]["theme"] = style_theme(_style_id)
    INDUSTRY_PRESETS[_industry_key]["operational_template"] = INDUSTRY_OPERATIONAL_TEMPLATES[_industry_key]

# The industry card in Studio Admin shows `slogan`; the site it publishes shows
# `hero.title`. Those were two hand-written strings, and in Chinese five of the
# eight had drifted apart — an owner picked 艺术 because the card promised
# 「大胆创作，让成长看得见。」 and the site went live saying
# 「让创意被看见，让成长有作品。」. In English they happened to be identical, so
# the fork was invisible to anyone reading the source in English.
#
# The hero title is now derived rather than written, so a card and the page it
# describes cannot disagree again. The subtitle stays hand-written: it is a
# different sentence doing a different job.
for _preset in INDUSTRY_PRESETS.values():
    _preset["hero"]["title"] = {"zh": _preset["slogan_zh"], "en": _preset["slogan"]}


def public_industry_presets() -> dict[str, dict]:
    """Return the client-safe preset shape used by both admin surfaces."""

    result: dict[str, dict] = {}
    for key, preset in INDUSTRY_PRESETS.items():
        result[key] = {
            "label": preset["label"],
            "labelZh": preset["label_zh"],
            "layout": preset["layout"],
            "slogan": preset["slogan"],
            "sloganZh": preset["slogan_zh"],
            "recommendedStyleId": preset["recommended_style_id"],
            "portalLabel": preset["copy_pack"]["portal_label"],
            "registerIntro": preset["copy_pack"]["register_intro"],
            "registerIntroZh": preset["register_intro_zh"],
            "registrationTitle": preset["registration_title"],
            "registrationTitleZh": preset["registration_title_zh"],
            # The public pages substitute these into %VENUE% / %WORK% / %WORKS%.
            # Without them the shared template calls every tenant a 画室 with
            # 作品, which is wrong for the piano, dance and game studios.
            "venueNoun": dict(preset["venue_noun"]),
            "workNoun": dict(preset["work_noun"]),
            "localizedCopy": {
                "hero_title": preset["hero"]["title"],
                "hero_subtitle": preset["hero"]["subtitle"],
                "primary_cta": {"zh": "预约体验", "en": "Book a Trial"},
                "secondary_cta": {"zh": "查看课程", "en": "Explore Programs"},
                "registration_title": {"zh": preset["registration_title_zh"], "en": preset["registration_title"]},
                "registration_intro": {"zh": preset["register_intro_zh"], "en": preset["copy_pack"]["register_intro"]},
                **INDUSTRY_SECTION_COPY.get(key, INDUSTRY_SECTION_COPY["general"]),
            },
            "visualTheme": dict(preset["theme"]),
            "registrationProfile": {"title": preset["registration_title"], "fields": [dict(field) for field in preset["fields"]]},
            "operationalTemplate": dict(preset["operational_template"]),
        }
    return result


def public_visual_style_presets() -> dict[str, dict]:
    """Return curated, client-safe visual styles with both scheme variants."""

    result: dict[str, dict] = {}
    for key, preset in VISUAL_STYLE_PRESETS.items():
        result[key] = {
            "label": preset["label"],
            "labelZh": preset["label_zh"],
            # 2-2: both languages ship, so the panel is not left translating an
            # English sentence through the admin dictionary at render time.
            "description": preset["description"],
            "descriptionZh": preset["description_zh"],
            "mood": preset["mood"],
            "harmony": preset["harmony"],
            "harmonyLabel": harmony_label(preset["harmony"]),
            "modes": list(preset["modes"]),
            # The editor needs both variants so it can preview a scheme switch
            # without another round trip.
            "schemes": {mode: style_theme(key, mode) for mode in preset["modes"]},
            "visualTheme": style_theme(key, preset["modes"][0]),
        }
    return result
