#!/usr/bin/env python3
"""Rotate every active privileged StudioSaaS account to a unique password.

The credential file is written with mode 0600 and is intentionally outside the
repository by default. Existing sessions remain valid; restart the application
after rotation when an immediate global sign-in reset is required.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import secrets
import sys
from pathlib import Path

APP_ROOT = Path(__file__).resolve().parents[1]
if str(APP_ROOT) not in sys.path:
    sys.path.insert(0, str(APP_ROOT))

PBKDF2_ITERATIONS = 600_000


def _legacy_cms_hash(password: str) -> str:
    """Return a hash compatible with the legacy CMS password file."""

    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, PBKDF2_ITERATIONS)
    return f"pbkdf2${PBKDF2_ITERATIONS}${salt.hex()}${digest.hex()}"


def _write_private_file(path: Path, content: str) -> None:
    """Write a UTF-8 file with owner-only permissions."""

    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(content)
    os.chmod(path, 0o600)


def rotate(output_path: Path, cms_password_path: Path) -> int:
    """Rotate database accounts and the separate legacy CMS password."""

    from studiosaas.auth import hash_password
    from studiosaas.db import connect

    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT DISTINCT u.id, lower(u.email) AS email
                FROM users u
                JOIN memberships m ON m.user_id = u.id
                WHERE u.status = 'active'
                  AND m.status = 'active'
                  AND m.role IN ('super_admin', 'owner', 'staff')
                ORDER BY lower(u.email)
                """
            )
            accounts = cur.fetchall()
            if not accounts:
                raise RuntimeError("No active privileged accounts were found.")
            credentials: list[tuple[str, str]] = []
            for account in accounts:
                password = secrets.token_urlsafe(18)
                cur.execute(
                    "UPDATE users SET password_hash = %s, updated_at = now() WHERE id = %s",
                    (hash_password(password), account["id"]),
                )
                credentials.append((account["email"], password))
        conn.commit()

    legacy_cms_password = secrets.token_urlsafe(18)
    _write_private_file(cms_password_path, _legacy_cms_hash(legacy_cms_password))
    credential_lines = [
        "# StudioSaaS privileged pilot credentials",
        "# Generated by rotate_pilot_credentials.py; do not commit.",
        *(f"{email}\t{password}" for email, password in credentials),
        f"legacy-cms\t{legacy_cms_password}",
    ]
    _write_private_file(output_path, "\n".join(credential_lines) + "\n")
    print(f"Rotated {len(credentials)} privileged account(s).")
    print(f"Rotated the legacy CMS password at {cms_password_path}.")
    print(f"Credentials written to {output_path} with mode 0600.")
    return len(credentials)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path.home() / ".studiosaas" / "pilot-credentials.txt",
        help="Protected credential output path.",
    )
    cms_data_dir = Path(os.environ.get("CMS_DATA_DIR", "").strip() or APP_ROOT)
    if not cms_data_dir.is_absolute():
        cms_data_dir = APP_ROOT / cms_data_dir
    parser.add_argument(
        "--cms-password-file",
        type=Path,
        default=cms_data_dir / ".cms_password",
        help="Legacy CMS password hash file used by the deployed server.",
    )
    args = parser.parse_args()
    rotate(args.output.expanduser().resolve(), args.cms_password_file.expanduser().resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
