#!/usr/bin/env python3
"""Rotate every active privileged StudioSaaS account to a unique password.

The credential file is written with mode 0600 and is intentionally outside the
repository by default. Existing sessions remain valid; restart the application
after rotation when an immediate global sign-in reset is required.
"""

from __future__ import annotations

import argparse
import os
import secrets
import sys
from pathlib import Path

APP_ROOT = Path(__file__).resolve().parents[1]
if str(APP_ROOT) not in sys.path:
    sys.path.insert(0, str(APP_ROOT))


def rotate(output_path: Path) -> int:
    from studiosaas.auth import hash_password
    from studiosaas.db import connect

    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT DISTINCT u.id, lower(u.email) AS email
                FROM users u
                JOIN memberships m ON m.user_id = u.id
                WHERE u.status = 'active'
                  AND m.status = 'active'
                  AND m.role IN ('super_admin', 'owner', 'staff')
                ORDER BY lower(u.email)
                """
            )
            accounts = cur.fetchall()
            if not accounts:
                raise RuntimeError("No active privileged accounts were found.")
            credentials: list[tuple[str, str]] = []
            for account in accounts:
                password = secrets.token_urlsafe(18)
                cur.execute(
                    "UPDATE users SET password_hash = %s, updated_at = now() WHERE id = %s",
                    (hash_password(password), account["id"]),
                )
                credentials.append((account["email"], password))
        conn.commit()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(output_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write("# StudioSaaS privileged pilot credentials\n")
        handle.write("# Generated by rotate_pilot_credentials.py; do not commit.\n")
        for email, password in credentials:
            handle.write(f"{email}\t{password}\n")
    os.chmod(output_path, 0o600)
    print(f"Rotated {len(credentials)} privileged account(s).")
    print(f"Credentials written to {output_path} with mode 0600.")
    return len(credentials)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path.home() / ".studiosaas" / "pilot-credentials.txt",
        help="Protected credential output path.",
    )
    args = parser.parse_args()
    rotate(args.output.expanduser().resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
