"""公开门户的四条：降级提示、选课上下文、约课报错、切语言不丢结果。

外加一条比这四条都重要的：**改了模板，生成器有没有跑过**。

`api_v1/misc.py:171` 的 `_workspace_drift` 只把 `tenants/<slug>/tenant.json` 里的
name 和数据库比一下，tenant.json 里没有模板版本也没有内容哈希。所以改完
`tenant-template/` 忘记跑 `regenerate_tenant_workspaces.py` 的后果是：线上健康
检查报 `workspaces.stale=0`、ui_matrix 全绿、测试全过，**而四个租户的公开页一个
字没变**。这一整批改动全部落在这条路径上。

`test_every_template_function_reaches_the_generated_pages` 就是那盏缺掉的红灯。
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
TEMPLATE = ROOT / "tenant-template"
TENANTS = ROOT / "tenants"

PORTAL = (TEMPLATE / "index.html").read_text(encoding="utf-8")
TIMETABLE = (TEMPLATE / "timetable.html").read_text(encoding="utf-8")


def _tenant_dirs() -> list[Path]:
    if not TENANTS.exists():
        return []
    return sorted(d for d in TENANTS.iterdir() if (d / "index.html").exists())


# ── 降级提示 ────────────────────────────────────────────────────────────


def test_a_degraded_page_shows_one_note_not_one_per_source() -> None:
    """五个数据源曾经就是五条横幅，叠在固定层里盖住 hero。"""

    assert "var surfaceFailures" in PORTAL, "失败的源要汇总，不能各画各的"
    render = PORTAL[PORTAL.index("function renderSurfaceStatus"):]
    render = render[:render.index("\n  function ")]
    assert render.count("createElement('div')") == 1, (
        "renderSurfaceStatus 只能画一条 note；每个源画一条正是原来的缺陷"
    )


def test_the_note_takes_space_instead_of_covering_the_hero() -> None:
    rule = re.search(r"\.surface-status\{([^}]*)\}", PORTAL)
    assert rule, ".surface-status 规则不见了"
    assert "position:fixed" not in rule.group(1), (
        "固定定位会把提示画在 hero 上；它应当占位而不是覆盖"
    )


def test_the_page_retries_by_itself_and_the_note_clears_on_success() -> None:
    """用户什么都不用做，才是这里的正确交互。"""

    assert "SURFACE_BACKOFF" in PORTAL and "scheduleSurfaceRetry" in PORTAL
    assert "function clearSurfaceStatus" in PORTAL
    # 每一个会失败的源都要在成功时把自己撤下来，否则提示永远挂着
    for source in ("brand", "programs", "gallery", "showcase"):
        assert f"clearSurfaceStatus('{source}')" in PORTAL, (
            f"{source} 加载成功后没有清掉自己的降级提示"
        )
    # 每一条 showSurfaceStatus 都要交出一个能重来的函数，否则重试无事可做
    for call in re.findall(r"showSurfaceStatus\('(\w+)',\s*([^)]+)\)", PORTAL):
        source, retry = call
        assert not retry.strip().startswith("T("), (
            f"{source} 传的还是一句文案；第二个参数现在是这个源自己的加载函数"
        )


# ── 选课上下文 ──────────────────────────────────────────────────────────


def test_a_course_card_carries_its_course_into_the_enquiry() -> None:
    assert "cta.dataset.course" in PORTAL and "setSelectedCourse(p.name" in PORTAL, (
        "每张课程卡的报名按钮以前都只是 #join，表单不知道他点的是哪一门"
    )
    assert 'id="joinCourse"' in PORTAL, "报名页要显示他正在咨询哪门课"
    assert "咨询课程: " in PORTAL, "这门课要真的进到工作室读得到的咨询内容里"


def test_the_chosen_course_survives_a_reload_and_a_language_switch() -> None:
    assert "searchParams.set('course'" in PORTAL, (
        "只存内存的话，切一次语言或者回退再进来就没了"
    )
    assert "searchParams.get('course')" in PORTAL
    assert "renderSelectedCourse();" in PORTAL


def test_the_chip_calls_it_an_enquiry_not_a_seat() -> None:
    """一条咨询不是一个席位。措辞错了会变成没兑现的承诺。"""

    assert "你正在咨询：" in PORTAL
    for wrong in ("已为你保留", "已预留席位", "报名成功"):
        assert wrong not in PORTAL[PORTAL.index('id="joinCourse"'):][:1500]


# ── 家长查询 ────────────────────────────────────────────────────────────


def test_switching_language_redraws_the_result_instead_of_hiding_it() -> None:
    """凭据还在、会话没过期，变的只是界面语言。"""

    assert "var lastStudentResult" in PORTAL
    assert "renderStudentPrivate(lastStudentResult)" in PORTAL, (
        "切换语言时要按新语言重画同一份结果，而不是 resetMyView() 把它藏起来"
    )
    reset = PORTAL[PORTAL.index("function resetMy()"):][:400]
    assert "lastStudentResult = null" in reset, "只有明确退出才清空"


# ── 公开约课 ────────────────────────────────────────────────────────────


def test_the_booking_form_marks_the_field_that_is_wrong() -> None:
    """实测对照：快速报名 focus=firstName、invalid=3；约课 focus=bookSubmit、invalid=0。"""

    assert "function failFirstBookingField" in TIMETABLE
    assert "aria-invalid" in TIMETABLE and "aria-describedby" in TIMETABLE, (
        "读屏要能知道是哪个字段、为什么无效"
    )
    assert "first.focus()" in TIMETABLE, "焦点要落在第一个错的字段上"


def test_a_parent_never_sees_a_machine_error_code() -> None:
    """服务端返回 validation_error 时，屏幕上曾经就写着 validation_error。"""

    body = TIMETABLE[TIMETABLE.index("const data = await response.json()"):][:1200]
    assert "data.message" in body, "可读的 message 要排在前面"
    assert not re.search(r"new Error\(data\.error\b", body), (
        "data.error 是机器码，不能直接上屏"
    )


# ── 这一批真正的风险：模板改了，生成器跑了没有 ──────────────────────────


# `tenants/isolation-*/` and `tenants/test-*/` are gitignored test residue, not
# customers; they are regenerated by whatever test last ran and are not part of
# the shipped surface.
def _shipped_tenant_dirs() -> list[Path]:
    return [d for d in _tenant_dirs()
            if not d.name.startswith(("isolation-", "test-"))]


@pytest.mark.skipif(not _shipped_tenant_dirs(), reason="no shipped tenant workspaces here")
def test_every_generated_workspace_is_byte_identical_to_a_fresh_render() -> None:
    """模板改了，生成器跑了没有——这条断言以前只比函数名。

    只比函数名的后果：改标记、改 CSS、改文案、改一个函数的函数体，全都看不见。
    而这一轮改的正是 `.reveal` 的 CSS 和一段内联脚本，函数名一个没动。

    改成用生成器**自己的代码路径**重渲染一遍再逐字节比对。不重新实现替换规则，
    所以生成器变了这条断言不会跟着漂；`{{TENANT_*}}` 的取值从每个租户自己的
    `tenant.json` 读回来，也就不需要在测试里复制一份。
    """

    import json
    import shutil
    import tempfile

    from studiosaas.workspaces import ensure_tenant_workspace

    compared = 0
    for tenant in _shipped_tenant_dirs():
        metadata = json.loads((tenant / "tenant.json").read_text(encoding="utf-8"))
        keep_local = {
            line.strip()
            for line in (tenant / ".keep-local").read_text(encoding="utf-8").splitlines()
            if (tenant / ".keep-local").is_file()
        } if (tenant / ".keep-local").is_file() else set()
        keep_local = {name for name in keep_local if name and not name.startswith("#")}

        with tempfile.TemporaryDirectory() as scratch:
            root = Path(scratch)
            shutil.copytree(TEMPLATE, root / "tenant-template")
            ensure_tenant_workspace(
                root, metadata["slug"], metadata["name"], metadata.get("head"))
            fresh = root / "tenants" / metadata["slug"]
            for rendered in sorted(fresh.iterdir()):
                if rendered.name in {"tenant.json"} | keep_local:
                    continue
                shipped = tenant / rendered.name
                assert shipped.is_file(), (
                    f"tenant-template/{rendered.name} has no counterpart in "
                    f"{tenant.name}/ —— 跑一次 regenerate_tenant_workspaces.py"
                )
                compared += 1
                if shipped.read_bytes() == rendered.read_bytes():
                    continue
                shipped_lines = shipped.read_text(encoding="utf-8").splitlines()
                fresh_lines = rendered.read_text(encoding="utf-8").splitlines()
                first = next(
                    (n for n, (a, b) in enumerate(zip(shipped_lines, fresh_lines), 1)
                     if a != b),
                    min(len(shipped_lines), len(fresh_lines)) + 1,
                )
                raise AssertionError(
                    f"{tenant.name}/{rendered.name} 与 tenant-template/ 重渲染的结果"
                    f"不一致，第 {first} 行起分歧：\n"
                    f"  产物: {(shipped_lines[first - 1:first] or [''])[0][:120]}\n"
                    f"  模板: {(fresh_lines[first - 1:first] or [''])[0][:120]}\n"
                    "改完 tenant-template/ 之后没有跑 "
                    "regenerate_tenant_workspaces.py。线上健康检查的 "
                    "workspaces.stale 只比租户名，不会报这件事。"
                )

    # 一个空循环也会「通过」。三个入库租户 × 五个模板文件。
    assert compared >= 15, f"只比对了 {compared} 个文件，断言的取材坏了"


@pytest.mark.skipif(not _tenant_dirs(), reason="no materialised tenant workspaces here")
def test_every_template_function_reaches_the_generated_pages() -> None:
    """模板里定义的每个函数，都必须出现在每个租户的产物里。

    这是 `workspaces.stale` 看不见的那种漂移。它只比名字，所以「改了模板没跑
    生成器」在健康检查、ui_matrix 和全量测试里都是全绿的——而访客看到的还是
    上一版的页面。

    断言按函数名做，不按整文件比对：生成器会替换 slug、工作室名和 head，
    整文件永远不相等。函数名不受这些替换影响，改代码就一定会动到它们。
    """

    for source, name in ((PORTAL, "index.html"), (TIMETABLE, "timetable.html")):
        expected = set(re.findall(r"function (\w+)\s*\(", source))
        assert expected, f"{name} 里一个函数都没找到，断言写错了"
        for tenant in _tenant_dirs():
            artefact = tenant / name
            if not artefact.exists():
                continue
            built = set(re.findall(r"function (\w+)\s*\(",
                                   artefact.read_text(encoding="utf-8")))
            missing = sorted(expected - built)
            assert not missing, (
                f"{tenant.name}/{name} 少了 {missing[:6]}——"
                "改完 tenant-template/ 之后没有跑 regenerate_tenant_workspaces.py。"
                "线上健康检查不会报这件事。"
            )


# ── 脚本抛了，页面还在不在 ──────────────────────────────────────────────


def test_the_tenant_portal_does_not_hide_itself_before_any_script_runs() -> None:
    """`.reveal{opacity:0}` 不带 `.js` 门控 = 脚本一抛，整页空白。

    营销页 2026-07 就修过这条（marketing.css:369 + marketing-shell.js:33，
    `test_product_home_brand.py` 钉着），租户模板没有。而两边的风险不对等：
    营销页的脚本是一个 51 行的 IIFE，租户模板的是 ~1,570 行**没有任何
    try 包裹的顶层语句**，第一句就读 `document.body.dataset` 和
    `window.StudioSaaS.esc`。任一处抛错，30 个内容块里 29 个永远停在
    opacity:0 —— 四个线上客户站是从这个模板生成的。
    """

    for name in ("index.html", "timetable.html", "showcase.html"):
        source = (TEMPLATE / name).read_text(encoding="utf-8")
        for line in _strip_css_comments(source).splitlines():
            stripped = line.strip()
            if ".reveal" not in stripped or "opacity:0" not in stripped.replace(" ", ""):
                continue
            assert stripped.startswith(".js "), (
                f"tenant-template/{name} 在任何脚本跑之前就把内容藏起来了：{stripped}"
            )

    portal = (TEMPLATE / "index.html").read_text(encoding="utf-8")
    assert "document.documentElement.classList.add('js')" in portal, (
        "没有人给 <html> 加 js —— 门控加了，开关没加，那是把整页永久显示"
    )
    # 开关必须挨着 reveal 的接线，不能挪到脚本顶部：挪上去，中间任何一处抛错
    # 又会把页面藏回去，而这正是这条断言要防的那件事。
    switch = portal.index("document.documentElement.classList.add('js')")
    wiring = portal.index("var io=new IntersectionObserver")
    assert 0 < switch - wiring < 700, (
        "js 开关离 reveal 接线太远；它必须在同一段里，否则中间抛错=空白页"
    )


def _strip_css_comments(source: str) -> str:
    return re.sub(r"/\*.*?\*/", "", source, flags=re.S)
